- README.md
- controller/test/README.md
- controller/test/checksum/checksum_test.cpp
- platformio.ini
Smoke tests for the checksum code, just to prove that testing is
happening.
<pr-train-toc>
👉 #76 (Add first controller unit test.) 👈 **YOU ARE HERE**
#82 (Fix fletcher16 checksum computation.)
</pr-train-toc>
> Add first controller unit test.

- controller/test/alarm/alarm_test.cpp
- controller/test/checksum/checksum_test.cpp
- controller/test/sensor_tests/SensorTests.cpp
The FullScaleReading test doesn't pass, so for now it's disabled.
@verityRF I believe you added this test, would you mind taking a look as to why it's failing? (to reproduce, simply remove `DISABLED_` and run `pio test -e native`)
> Moves all tests to googletest

- controller/include/command.h
- controller/include/comms.h
- controller/include/serialIO.h
- controller/include/solenoid.h
- controller/lib/hal/hal.h
- controller/src/comms.cpp
- controller/src/eeprom.cpp
- controller/src/parameters.cpp
- controller/src/pid.cpp
- controller/src/serialIO.cpp
- controller/src/solenoid.cpp
- controller/src/ventilator.cpp
- controller/src/version.cpp
Adds some more functionality to HAL and converts a few more files to use it.
> Some HAL fixups.

- .pre-commit-config.yaml
protos are added in https://github.com/RespiraWorks/VentilatorSoftware/pull/125.
> Add pre-commit rule to format .proto files.

- gui/ControlPanel.qml
My first pass at showing the current ventilator state.  Give it a try and let me know what you think!
I was hoping to hide the graphs when the ventilator is off but I need to read some more about Qt first.
Couple questions:
Is it okay to have the OFF indicator be in the same text box as the modes?  Seems like we don't need to indicate a mode and that the unit is off.
Do we want colors to indicate modes?
Let me know if I'm breaking any normal Qt conventions.
> First pass at displaying the ventilator mode/state

- platformio.ini
I...guess I understand why this is on by default.  Do not want.
> Don't compile with -fpermissive.

- .circleci/config.yml
- .gitignore
- .pre-commit-config.yaml
- .travis.yml
- common/test_libs/README.md
- gui/Dockerfile
- gui/ProjectVentilatorGUI.pro
- gui/build.sh
- test.sh
Bonus: Adds additional style checks to pre-commit.
> Make travis trigger precommit

- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/src/main.cpp
- controller/src/pid.cpp
- controller/test/sensor_tests/SensorTests.cpp
Additions to sensor.cpp to enable closing Issue #101.
Adds volumetric flow calculation based on Bernoulli's from differential pressure input.
Very, very simple unit test confirms operation.
Uses Ethan's suggested Venturi diameters; module allows the diameters to be changed later easily.
Moved sensors_init after blowers_init in the main loop because the sensors module requires  the blowers to be off for calibration (how can you disable the blower when that module isn't initialized?)
> Works on Issue #101

- controller/test/alarm/alarm_test.cpp
- controller/test/parameters/parameters_test.cpp
Added some simple unit tests to alarms and for the parameter config bounding
> Sarah adelaide/unit tests

- .ycm_extra_conf.py
<git-pr-chain>
1. Add PID_ID2 to YCM include path.
1. 👉 #162 jlebar/ycm-flags 👈 **YOU ARE HERE**
> Add PID_ID2 to YCM include path.

- controller/src/pid.cpp
As per conversation with Edwin, figured out what the 3 reading parameters are supposed to be in regards to the actual air circuits.
This would close out the original Issue #101, leaving the volume for a later time which is now a beta function anyway.
> Update pid.cpp to fix flow reporting

- controller/lib/hal/hal.h
<git-pr-chain>
1. Clarify that HAL is not a mock.
When I wrote it, I was anticipating it would be half-mock, half-fake.
We seem to be getting along fine with all-fake no-mock, so clarify the
comments.
Also link to the canonical list of parts, and get rid of unnecessary
enum int types (the compiler will chose them for us, this is an advanced
feature really only needed for cross-platform ABI compatibility and such).
1. 👉 #190 Clarify that HAL is not a mock. 👈 **YOU ARE HERE**
1. #198 Fix ODR violation on map() function.
1. #193 Simplify blower PID state machine.
1. #194 Disable modernize-use-default-member-init clang-tidy warning
1. #195 Rename algorithm/alg -> stl/algorithm.h.
1. #197 Remove some unused options in network_protocol.proto.
1. #202 Blacklist …
> Clarify that HAL is not a mock.

- controller/lib/core/control.cpp
<git-pr-chain>
1. Simplify blower PID state machine.
Edwin suggested that we should dive PID to blow a square wave rather
than a trapezoid.  Who knows, maybe a trapezoid is necessary, but it's
not necessary for alpha.
1. 👉 #193 Simplify blower PID state machine. 👈 **YOU ARE HERE**
1. #194 Disable modernize-use-default-member-init clang-tidy warning
1. #195 Rename algorithm/alg -> stl/algorithm.h.
1. #197 Remove some unused options in network_protocol.proto.
1. #202 Blacklist -misc-non-private-member-variables-in-classes clang-tidy check.
> Simplify blower PID state machine.

- .travis.yml
- gui/ControlPanel.qml
- gui/ProjectVentilatorGUI.pro
- gui/ScopeView.qml
- gui/build.sh
- gui/datasource.cpp
- gui/datasource.h
- gui/main.cpp
- gui/main.qml
Also prepares datasource to be connectable to real data.
In next PRs I'll remove more cruft and make the mechanism of obtaining data yet a bit more realistic.
> Removes some (far from all) of the unnecessary cruft in gui.

- common/libs/units/units.cpp
- common/libs/units/units.h
- controller/lib/core/control.cpp
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/lib/hal/hal.h
- controller/test/sensor_tests/SensorTests.cpp
- controller/test/units/units_test.cpp
<git-pr-chain>
1. Add and use units library.
Currently knows about pressure, volumetric flow, time, and duration.
1. 👉 #201 Add and use units library. 👈 **YOU ARE HERE**
1. #202 Blacklist -misc-non-private-member-variables-in-classes clang-tidy check.
> Add and use units library.

- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
<git-pr-chain>
1. Rejigger sensors constants.
Move some out of the header file.
1. 👉 #203 Rejigger sensors constants. 👈 **YOU ARE HERE**
> Rejigger sensors constants.

- controller/lib/core/blower_fsm.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Make VentMode_PRESSURE_CONTROL work.
Fix a bug and add a test.
1. 👉 #222 Make VentMode_PRESSURE_CONTROL work. 👈 **YOU ARE HERE**
1. #212 Fix pressure sensors pinout.
1. #216 Explicitly set the output limits in our blower PID.
1. #217 Control the solenoid from the Blower FSM.
1. #218 Add NO_GUI_DEV_MODE, for running the controller without a GUI.
> Make VentMode_PRESSURE_CONTROL work.

- controller/lib/hal/hal.h
<git-pr-chain>
1. Fix pressure sensors pinout.
Currently pressure sensors are connected to A5/6/7 per the spreadsheet.
1. 👉 #212 Fix pressure sensors pinout. 👈 **YOU ARE HERE**
1. #216 Explicitly set the output limits in our blower PID.
1. #217 Control the solenoid from the Blower FSM.
1. #218 Add NO_GUI_DEV_MODE, for running the controller without a GUI.
> Fix pressure sensors pinout.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/blower_pid.cpp
- controller/lib/core/blower_pid.h
- controller/lib/hal/hal.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Control the solenoid from the Blower FSM.
Fixes https://github.com/RespiraWorks/VentilatorSoftware/issues/213.
1. 👉 #217 Control the solenoid from the Blower FSM. 👈 **YOU ARE HERE**
1. #218 Add NO_GUI_DEV_MODE, for running the controller without a GUI.
> Control the solenoid from the Blower FSM.

- controller/src/main.cpp
<git-pr-chain>
1. Add NO_GUI_DEV_MODE, for running the controller without a GUI.
Super hacky, I apologize.
1. 👉 #218 Add NO_GUI_DEV_MODE, for running the controller without a GUI. 👈 **YOU ARE HERE**
> Add NO_GUI_DEV_MODE, for running the controller without a GUI.

- common/libs/units/units.h
- controller/lib/core/blower_pid.cpp
- controller/src/main.cpp
- controller/test/units/units_test.cpp
<git-pr-chain>
1. First pass at tidal volume measurement.
Fixes #214.
1. 👉 #232 First pass at tidal volume measurement. 👈 **YOU ARE HERE**
1. #233 Re-tune PID.
1. #234 Change default params in DEV_MODE_comms_handler.
> First pass at tidal volume measurement.

- controller/src/main.cpp
<git-pr-chain>
1. Change default params in DEV_MODE_comms_handler.
The old params -- PIP 30 PEEP 10 -- were hard for us to meet, and thus
complicated testing.
1. 👉 #234 Change default params in DEV_MODE_comms_handler. 👈 **YOU ARE HERE**
> Change default params in DEV_MODE_comms_handler.

- common/libs/checksum/checksum.cpp
- common/libs/checksum/checksum.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/test/checksum/checksum_test.cpp
Also adds soft crc32 function compatible with STM32 CRC32.
> Issue #159 add STM32 CRC32 HAL.

- controller/lib/core/debug.cpp
- controller/lib/core/debug.h
- controller/lib/core/sprintf.cpp
- controller/lib/core/sprintf.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- controller/src/main.cpp
Added a second serial port to the HAL for debug use.  On the nucleo board, this serial port is indirectly connected to the virtual USB serial port.
Also added a printf style function for printing to this port.  The standard library sprintf functions dynamically allocate memory which we don't do on our controller, so I added a sprintf implementation which I wrote that does not allocate any RAM.
> Issue 277 debug serial

- controller/lib/hal/hal.h
<git-pr-chain>
1. Unbreak nucleo build.
This wasn't running in CI yet, but I'm about to add it.
1. 👉 #298 Unbreak nucleo build. 👈 **YOU ARE HERE**
1. #299 Fix sprintf build on my machine.
1. #284 Remove stl::min/max/clamp.
> Unbreak nucleo build.

- controller/lib/core/sensors.cpp
<git-pr-chain>
1. Use C++ STL math functions in sensors.cpp.
Fixes a TODO and lets us use a bit more constexpr.
1. 👉 #285 Use C++ STL math functions in sensors.cpp. 👈 **YOU ARE HERE**
> Use C++ STL math functions in sensors.cpp.

- utils/decoder.py
<git-pr-chain>
1. Reformat decoder.py.
Run `black` over it.
1. 👉 #286 Reformat decoder.py. 👈 **YOU ARE HERE**
> Reformat decoder.py.

- .gitignore
<git-pr-chain>
1. Add __pycache__ to gitignore.
1. 👉 #287 Add __pycache__ to gitignore. 👈 **YOU ARE HERE**
> Add __pycache__ to gitignore.

- controller/lib/hal/hal.h
<git-pr-chain>
1. Update pinout in HAL for STM32.
1. 👉 #288 Update pinout in HAL for STM32. 👈 **YOU ARE HERE**
> Update pinout in HAL for STM32.

- controller/lib/core/sensors.cpp
<git-pr-chain>
1. Update comment in sensors.cpp for STM32.
1. 👉 #289 Update comment in sensors.cpp for STM32. 👈 **YOU ARE HERE**
> Update comment in sensors.cpp for STM32.

- gui/build.sh
<git-pr-chain>
1. gui/build.sh: Build GUI in parallel.
s/make/make -j/
1. 👉 #290 gui/build.sh: Build GUI in parallel. 👈 **YOU ARE HERE**
> gui/build.sh: Build GUI in parallel.

- controller/src/main.cpp
<git-pr-chain>
1. Unbreak DEV_MODE build.
1. 👉 #291 Unbreak DEV_MODE build. 👈 **YOU ARE HERE**
> Unbreak DEV_MODE build.

- .pre-commit-config.yaml
- .ycm_extra_conf.py
- boards/stm32_scripts.py
- platformio_sanitizers.py
- utils/mock-cycle-controller.py
- utils/nanopb_pb2.py
- utils/network_protocol_pb2.py
<git-pr-chain>
1. Add+run precommit for the 'black' Python formatter
1. 👉 #292 Add+run precommit for the 'black' Python formatter 👈 **YOU ARE HERE**
> Add+run precommit for the 'black' Python formatter

- .clang-tidy
- .ycm_extra_conf.py
<git-pr-chain>
1. Tweak clang-tidy and YCM flags.
Trying to make the warnings a bit less noisy.
1. 👉 #296 Tweak clang-tidy and YCM flags. 👈 **YOU ARE HERE**
> Tweak clang-tidy and YCM flags.

- README.md
<git-pr-chain>
1. Update badges in README.md.
Having some fun with these badges.
1. 👉 #294 Update badges in README.md. 👈 **YOU ARE HERE**
1. #310 Delete nucleo board.
1. #311 Tweak SensorReadings proto.
1. #312 Make Hal::analog{Read,Write} use Voltages.
> Update badges in README.md.

- controller/lib/hal/hal.h
- platformio.ini
- test.sh
<git-pr-chain>
1. Delete nucleo board.
I've verified that the `stm32` target works!
1. 👉 #310 Delete nucleo board. 👈 **YOU ARE HERE**
1. #311 Tweak SensorReadings proto.
1. #312 Make Hal::analog{Read,Write} use Voltages.
1. #313 Add BlockInterrupts RAII class.
> Delete nucleo board.

- gui/rpi-image/README.md
<git-pr-chain>
1. Fix trailing whitespace in a README.md file.
1. 👉 #293 Fix trailing whitespace in a README.md file. 👈 **YOU ARE HERE**
> Fix trailing whitespace in a README.md file.

- controller/test/sensor_tests/sensors_test.cpp
Sorry, rebased & merged a PR and only afterword realized that one of the tests was failing.
Very minor fix to make the test compatible with the updated codebase.
> Fixed a couple sensor tests

- controller/lib/core/sensors.cpp
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- platformio.ini
<git-pr-chain>
1. Oversample sensor readings in hardware.
Honestly this doesn't seem to help a ton, but (a) it's a simplification
to the sensor code, and (b) it lets us experiment with oversampling even
if this first experiment is unsuccessful.
1. 👉 #330 Oversample sensor readings in hardware. 👈 **YOU ARE HERE**
> Oversample sensor readings in hardware.

- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/uart_dma.cpp
<git-pr-chain>
1. Bitfield-ify UART status register.
1. #337 Move sprintf.{h,cpp} to new debug library.
1. #338 Fix Flash/RAM size in STM32 board config.
1. #339 Bitfield-ify UART timeout field.
1. #340 Bitfield-ify UART `request` field.
1. 👉 #341 Bitfield-ify UART status register. 👈 **YOU ARE HERE**
> Bitfield-ify UART status register.

- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/uart_dma.cpp
<git-pr-chain>
1. Bitfield-ify UART timeout field.
1. 👉 #347 Bitfield-ify UART timeout field. 👈 **YOU ARE HERE**
1. #340 Bitfield-ify UART `request` field.
1. #348 Bitfield-ify UART status register.
> Bitfield-ify UART timeout field.

- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/uart_dma.cpp
<git-pr-chain>
1. Bitfield-ify UART `request` field.
1. 👉 #340 Bitfield-ify UART `request` field. 👈 **YOU ARE HERE**
1. #348 Bitfield-ify UART status register.
> Bitfield-ify UART `request` field.

- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/uart_dma.cpp
<git-pr-chain>
1. Bitfield-ify UART intClear register.
1. 👉 #342 Bitfield-ify UART intClear register. 👈 **YOU ARE HERE**
> Bitfield-ify UART intClear register.

- controller/lib/core/circular_buffer.h
- controller/lib/hal/hal_stm32.cpp
- controller/src/main.cpp
- controller/test/circ_buff/circ_buff_test.cpp
<git-pr-chain>
1. Templatize CircularBuffer's datatype.
1. 👉 #344 Templatize CircularBuffer's datatype. 👈 **YOU ARE HERE**
> Templatize CircularBuffer's datatype.

- controller/lib/core/circular_buffer.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/stepper.cpp
- controller/lib/hal/stepper.h
- controller/lib/hal/uart_dma.cpp
- controller/src/main.cpp
- scripts/peek_dma.py
- scripts/read_motor_params.py
This PR creates a driver for the stepper motors used to actuate the pinch valves.
> Issue 325 motor driver

- .github/ISSUE_TEMPLATE/task.md
I want to create new issue to assign myself a task
> add task github issue template

- common/libs/units/units.h
- controller/lib/core/sensors.cpp
- controller/lib/hal/hal_stm32.cpp
- controller/test/units/units_test.cpp
Added a couple useful debug variables for tracing sensor readings and loop timing.
> Added a couple handy debug vars for tracing

- controller/lib/debug/debug.cpp
- controller/lib/debug/debug.h
- controller/lib/debug/pb_read_cmd.h
- controller/lib/debug/peek_cmd.h
- controller/lib/debug/poke_cmd.h
- controller/lib/debug/trace_cmd.cpp
- controller/lib/debug/trace_cmd.h
- controller/lib/debug/var_cmd.cpp
- controller/lib/debug/var_cmd.h
- controller/test/debug/var_cmd_test.cpp
This will make it easier to instead pass a request and response protobuf.<git-pr-chain>
1. Separates the request and response buffers in DebugCmd
This will make it easier to instead pass a request and
response protobuf.
1. 👉 #382 Separates the request and response buffers in DebugCmd 👈 **YOU ARE HERE**
1. #385 Puts tracing into a class.
> Separates the request and response buffers in DebugCmd

- .gitignore
- controller/lib/core/controller.cpp
- controller/lib/debug/debug.cpp
- controller/lib/debug/vars.h
- controller/src/main.cpp
- utils/controller_debug.py
Added some new Debug var sub-classes for convenience.
Also added debug variables to control the controller when no GUI is present.
> Minor debug improvements

- .clang-tidy
- controller/lib/debug/trace.cpp
- controller/lib/debug/trace.h
- controller/lib/debug/trace_cmd.cpp
- controller/lib/debug/var_cmd.cpp
- controller/lib/debug/vars.cpp
- controller/lib/debug/vars.h
- controller/src/main.cpp
* Pulls out a base class from `DebugVar`, in order to have another subclass FnDebugVar that has getters and setters for lambdas. This is handy for having them call someone's methods - in this case, setter methods on the `TraceControl` class
* Centralizes tracing in the `TraceControl` class, including flushing when a new trace is started, etc. (some of that code was scattered around)
* We don't need the variable for counting trace samples as it equals trace buffer size / num variables.
The next step will be to also pull control of which variables are traced into methods of `TraceControl`, and add unit tests for tracing.<git-pr-chain>
1. Puts tracing into a class.
1. 👉 #385 Puts tracing into a class. 👈 **YOU ARE HERE**
> Puts tracing into a class.

- platformio.ini
… by disabling compiler optimizations
> Add a temporary band aid for #393 to unbreak the system

- README.md
- boards/README.md
- common/README.md
- controller/README.md
- gui/README.md
- sample-data/README.md
- scripts/README.md
- utils/README.md
I more or less know what it's all about, but I'm gonna try to make things more explicit. I'm using this PR as an opportunity to get all y'all's feedback on what that content should be. If you answer to any of my **TODOs** I'll be more than happy to will that content out and format it all user friendly like.
> Improving in-repo documentation

- controller/lib/hal/hal.h
- platformio.ini
<git-pr-chain>
1. Build with -fno-exceptions.
1. 👉 #411 Build with -fno-exceptions. 👈 **YOU ARE HERE**
1. #412 Build with -fno-rtti.
1. #413 Add an implementation of __cxa_pure_virtual.
> Build with -fno-exceptions.

- boards/stm32_scripts.py
<git-pr-chain>
1. Build with -fno-rtti.
Per this guide to disabling exceptions in embedded C++:
http://elegantinvention.com/blog/information/smaller-binary-size-with-c-on-baremetal-g/
1. 👉 #412 Build with -fno-rtti. 👈 **YOU ARE HERE**
1. #413 Add an implementation of __cxa_pure_virtual.
> Build with -fno-rtti.

- .clang-tidy
- controller/lib/debug/debug.cpp
- controller/lib/debug/debug.h
- controller/lib/hal/hal.h
- controller/test/debug/debug_test.cpp
- platformio.ini
<git-pr-chain>
1. Do not reuse buffer index between request and response.
Also:
* Adds functions for testing the debug serial port to HAL
* Adds a basic test of the Debug interface (just two commands for now)
1. 👉 #391 Do not reuse buffer index between request and response. 👈 **YOU ARE HERE**
1. #392 Centralizes trace management completely in the Trace class and adds tests.
> Do not reuse buffer index between request and response.

- utils/controller_debug.py
<git-pr-chain>
1. Sort includes in controller_debug.py.
1. 👉 #429 Sort includes in controller_debug.py. 👈 **YOU ARE HERE**
1. #430 controller_debug: Print help for trace.
1. #431 Fix typo: seperate -> separate.
> Sort includes in controller_debug.py.

- utils/controller_debug.py
<git-pr-chain>
1. Fix typo: seperate -> separate.
1. 👉 #431 Fix typo: seperate -> separate. 👈 **YOU ARE HERE**
> Fix typo: seperate -> separate.

- utils/controller_debug.py
<git-pr-chain>
1. Add documentation for `exec` command.
1. 👉 #436 Add documentation for `exec` command. 👈 **YOU ARE HERE**
> Add documentation for `exec` command.

- utils/controller_debug.py
<git-pr-chain>
1. Tighten up trace documentation a bit.
1. 👉 #437 Tighten up trace documentation a bit. 👈 **YOU ARE HERE**
> Tighten up trace documentation a bit.

- utils/controller_debug.py
<git-pr-chain>
1. Use argparse for `trace download` and `console`.
Using argparse is less code and gives more helpful errors, but more
importantly it will allow us to parse more complicated subcommands.
1. 👉 #438 Use argparse for `trace download` and `console`. 👈 **YOU ARE HERE**
> Use argparse for `trace download` and `console`.

- utils/controller_debug.py
<git-pr-chain>
1. Fix up docstrings.
- Make some comments into docstrings.
- Complete incomplete docstring on TraceDownload.
- Format docstrings so the first line isn't empty (PEP 257)
1. 👉 #445 Fix up docstrings. 👈 **YOU ARE HERE**
1. #446 Add arguments to `trace start` command.
1. #447 Auto-detect port device is connected to.
1. #448 Tweak implementation of TraceDownload.
1. #449 Label axes and lines in graph.
> Fix up docstrings.

- utils/controller_debug.py
<git-pr-chain>
1. Add arguments to `trace start` command.
You can now do e.g. `trace start --period 10 volume flow_diff`.
1. 👉 #446 Add arguments to `trace start` command. 👈 **YOU ARE HERE**
1. #447 Auto-detect port device is connected to.
1. #448 Tweak implementation of TraceDownload.
1. #449 Label axes and lines in graph.
> Add arguments to `trace start` command.

- utils/controller_debug.py
<git-pr-chain>
1. Auto-detect port device is connected to.
1. 👉 #447 Auto-detect port device is connected to. 👈 **YOU ARE HERE**
1. #448 Tweak implementation of TraceDownload.
1. #449 Label axes and lines in graph.
> Auto-detect port device is connected to.

- utils/controller_debug.py
<git-pr-chain>
1. Tweak implementation of TraceDownload.
No functional change, just more comments and a different implementation.
1. 👉 #448 Tweak implementation of TraceDownload. 👈 **YOU ARE HERE**
1. #449 Label axes and lines in graph.
> Tweak implementation of TraceDownload.

- utils/controller_debug.py
<git-pr-chain>
1. Label axes and lines in graph.
- Label x axis as seconds (and scale according to trace period).
- Label individual lines according to what we're graphing, e.g.
"Tidal volume, ml".
1. 👉 #449 Label axes and lines in graph. 👈 **YOU ARE HERE**
> Label axes and lines in graph.

- utils/controller_debug.py
<git-pr-chain>
1. Use /usr/bin/env python3 as shebang.
This way we pull whatever is the user's default python3, instead of
forcing /usr/bin/python3.
1. 👉 #451 Use /usr/bin/env python3 as shebang. 👈 **YOU ARE HERE**
> Use /usr/bin/env python3 as shebang.

- utils/controller_debug.py
<git-pr-chain>
1. Add -c flag.
Lets you run a single command, e.g.
controller_debug.py -c "trace start volume" && sleep 10 &&
controller_debug.py -c "trace graph"
Currently, there's no way to do multiple commands except by multiple
invocations of the script.
1. 👉 #452 Add -c flag. 👈 **YOU ARE HERE**
> Add -c flag.

- controller/lib/core/sensors.cpp
<git-pr-chain>
1. Add debug var for tidal volume.
1. 👉 #453 Add debug var for tidal volume. 👈 **YOU ARE HERE**
> Add debug var for tidal volume.

- .gitignore
<git-pr-chain>
1. gitignore .pytype/
1. 👉 #459 gitignore .pytype/ 👈 **YOU ARE HERE**
1. #460 Highlight the y=0 gridline.
1. #461 Units: Add missing `const` modifiers.
> gitignore .pytype/

- utils/controller_debug.py
<git-pr-chain>
1. Highlight the y=0 gridline.
Makes it easier to see where zero is.
1. 👉 #460 Highlight the y=0 gridline. 👈 **YOU ARE HERE**
1. #461 Units: Add missing `const` modifiers.
> Highlight the y=0 gridline.

- common/libs/units/units.h
<git-pr-chain>
1. Units: Add missing `const` modifiers.
Some member functions weren't marked as const.
Also remove some unnecessary `inline`s.
1. 👉 #461 Units: Add missing `const` modifiers. 👈 **YOU ARE HERE**
> Units: Add missing `const` modifiers.

- controller/lib/core/actuators.cpp
- controller/lib/core/actuators.h
- controller/lib/core/controller.cpp
- controller/lib/core/pinch_valve.cpp
- controller/lib/core/pinch_valve.h
- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/src/main.cpp
- controller/test/pid_lib/pid_test.cpp
This is another attempt at adding PID control of pressure to the controller.
I have attempted to minimize the changes to other parts of the code in this version so hopefully it will be more palatable.
> Implemented PID control of pressure

- common/libs/units/units.h
- controller/lib/core/comms.cpp
- controller/lib/hal/adc.cpp
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32_regs.h
- controller/lib/pid/pid.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
- controller/test/pid_lib/pid_test.cpp
- controller/test/sensor_tests/sensors_test.cpp
- controller/test/units/units_test.cpp
<git-pr-chain>
1. Granularity of Time and Duration 1ms -> 1us.
Motivation: The high-priority loop runs once every few ms, so just a
timer granularity of 1ms is very coarse compared to what's happening in
the system.
1. 👉 #465 Granularity of Time and Duration 1ms -> 1us. 👈 **YOU ARE HERE**
1. #467 Remove sample-time checking from PID.
> Granularity of Time and Duration 1ms -> 1us.

- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. Fix units errors in sensors_test.
In multiple places in sensors_test, we use a tolerance in one unit (e.g.
kPa) to compare two values in a different unit (e.g. cmh2o).
Fix this by introducing EXPECT_{FLOW,PRESSURE,VOLUME}_NEAR macros.
1. 👉 #474 Fix units errors in sensors_test. 👈 **YOU ARE HERE**
1. #477 Move setpoint_pressure field into ControllerState.
> Fix units errors in sensors_test.

- controller/lib/hal/buzzer.cpp
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
This adds support for the buzzer on the controller board
> Added support for the controller audio alarm

- utils/controller_debug.py
Timestamps are added to saved trace data
controller is queried to find sample time rather then hard code it
> Minor improvements to data tracing

- sample-data/README.md
<git-pr-chain>
1. Remove trailing whitespace in sample-data/README.md
1. 👉 #495 Remove trailing whitespace in sample-data/README.md 👈 **YOU ARE HERE**
1. #485 Units: Allow x / y to return a raw ratio.
1. #486 Move blower_fsm implementations into cpp file.
> Remove trailing whitespace in sample-data/README.md

- controller/lib/core/controller.cpp
- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/test/pid_lib/pid_test.cpp
Also reset PID state when ventilator is off
> Adjusted PID tuning to make system more stable.

- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/src/main.cpp
<git-pr-chain>
1. Eagerly home pinch valves.
Instead of homing them when you first start ventilation and then
hard-disabling them when you stop (requiring re-homing before we begin
again).
Also fix a TODO in controller.cpp.
Note that the stepper motors consume a nontrivial amount of power in
this mode.
1. 👉 #497 Eagerly home pinch valves 👈 **YOU ARE HERE**
> Eagerly home pinch valves

- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/src/main.cpp
- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. Separate SensorReadings from SensorsProto.
SensorReadings is strongly-typed, SensorsProto is weakly-typed.
Also in a future PR, I will remove volume from SensorReadings and move
it into ControllerStatus.  The proto will remain unchanged.
Based on #478 by @asmodai27.
Closes #478.
1. 👉 #499 SensorReadings from SensorsProto. 👈 **YOU ARE HERE**
> SensorReadings from SensorsProto.

- .pre-commit-config.yaml
<git-pr-chain>
1. Run clang-format over the whole file.
Instead of formatting just the lines you've changed.
See long explanation at
https://github.com/jlebar/pre-commit-hooks/commit/349213c5414e360385e74f04964e6d5c43cdad36#diff-04c6e90faac2675aa89e2176d2eec7d8
1. 👉 #500 Run clang-format over the whole file. 👈 **YOU ARE HERE**
1. #501 ControllerStatus.fan_setpoint -> pressure_setpoint.
1. #502 Rename setpoint_pressure -> pressure_setpoint.
> Run clang-format over the whole file.

- .gitignore
- controller/lib/hal/README.md
- controller/lib/hal/adc.cpp
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- controller/lib/hal/hal_stm32_regs.h
- sample-data/README.md
Added references for registers, notes for bit manipulation, and the reference manuals' procedures to go with functions.
Addresses some of #352
> Documentation for STM32 HAL (with pre-commit)

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
Inspiratory effort detection is very crude and probably not reliable. This is mostly setting up the framework to unblock GUI and start working on the actual solution for inspiratory effort detection.
Note: I updated proto file but also updated network_protocol.pb.h manually (couldn't get nanopb to run...), please double check both those files!
> First pass at Pressure Assist Mode.

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/src/main.cpp
- utils/mock-cycle-controller.py
- utils/network_protocol_pb2.py
<git-pr-chain>
1. ControllerStatus.fan_setpoint -> pressure_setpoint.
Simple rename, no functional change.
1. 👉 #501 ControllerStatus.fan_setpoint -> pressure_setpoint. 👈 **YOU ARE HERE**
1. #502 Rename setpoint_pressure -> pressure_setpoint.
1. #504 BlowerFsm API cleanups.
1. #505 Move volume sensing into controller.
1. #506 Delete unused VentParams.rise_time_ms.
> ControllerStatus.fan_setpoint -> pressure_setpoint.

- controller/integration_tests/solenoid_test.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/psol.cpp
This adds basic support for the PSOL to the HAL
> Added PSOL support

- gui/app/controls/ParameterAdjustPopup.qml
- gui/app/modes/CommandPressureMode.qml
> [GUI] Keep Respiratory Rate range between 10-30 bpm.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/test/blower_fsm/blower_fsm_test.cpp
Reuse of the code from pressure control mode.
I assumed that RISE_TIME is not dependent on the ventilator mode, please correct me if I am wrong.
> Rise from PEEP to PIP in 100 ms in pressure assist mode

- gui/app/main.cpp
- gui/app/modes/CommandPressureMode.qml
- gui/app/qml.qrc
- gui/app/sample-data
- gui/src/gui_state_container.cpp
- gui/src/gui_state_container.h
Also fixes some units in GUI code to make this sample data look more reasonable (though still really only the pressure looks reasonable; flow is noticeable but kinda too low and noisy; and volume is meaningless to display cause in this file it is uncorrected).
The point of this is that when in other PRs that I'm preparing I start working with breath boundaries in the GUI (e.g. computed PIP/PEEP, alarms thereon), I'd like to work with at least somewhat realistic data.
> In fake mode, reads GUI data from one of the sample files

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/src/main.cpp
- controller/test/controller/controller_test.cpp
- utils/network_protocol_pb2.py
This is so that we can detect breath boundaries in the GUI to measure PIP/PEEP and compute alarms on them.
> Adds breath_id to network protocol and fills it in on the controller

- gui/app/main.qml
- gui/app/modes/CommandPressureMode.qml
- gui/app/modes/PressureAssistMode.qml
- gui/src/gui_state_container.h
<git-pr-chain>
1. GUI: Implement PressureAssistMode.
Copy-pasted CommandPressureMode -> PressureAssistMode per @jkff.
Verified that the GuiStatus in main.cpp's Communicate() sends the
correct mode when it's changed.
1. 👉 #520 GUI: Implement PressureAssistMode. 👈 **YOU ARE HERE**
> GUI: Implement PressureAssistMode.

- utils/controller_debug.py
<git-pr-chain>
1. controller_debug; Add variable presets.
This lets you say e.g. "preset covent_pc_3" to load a particular set of
parameters.
1. 👉 #521 controller_debug; Add variable presets. 👈 **YOU ARE HERE**
> controller_debug; Add variable presets.

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/lib/core/blower_fsm.cpp
- gui/app/main.qml
- gui/app/modes/PressureAssistMode.qml
- gui/src/gui_state_container.h
- utils/network_protocol_pb2.py
Adds HFNC mode to the proto as a formality.
> Changes ventilation mode property to be an enum.

- gui/app/main.cpp
- gui/src/gui_state_container.h
Extracted out of https://github.com/RespiraWorks/VentilatorSoftware/pull/517 for easier review.
Makes GuiStateContainer a regular QObject obeying QT threading logic instead of using its own mutex. I did this because:
* Both comms thread (gui/controller status exchange) and GUI thread need to talk to the alarm state
* I want MaxPressureAlarm to be a property of GuiStateContainer, because alarm state is GUI state
* Using a mutex in GuiStateContainer meant that GuiStateContainer manages thread safety, but it cannot manage thread safety transitively through MaxPressureAlarm, and I don't want to add mutexes to the alarm.
* So it's much easier to use regular QObject's and handle interaction with the comms thread via Qt queued signal connections (when invoked from a thread other than the …
> Moves thread safety out of GuiStateContainer

- utils/controller_debug.py
<git-pr-chain>
1. Enhancements to `trace graph`.
Add --dest, --title, and --nointeractive flags.
Together these let us use trace graph from a script that will run
multiple presets.
1. 👉 #532 Enhancements to `trace graph`. 👈 **YOU ARE HERE**
1. #533 Add --detect-port-and-quit flag to controller_debug.py.
1. #534 Add scaling support to trace graph.
1. #535 Set gui_mode last when applying a preset.
1. #536 Add script to run all covent tests in a row.
> Enhancements to `trace graph`.

- utils/controller_debug.py
<git-pr-chain>
1. Add --detect-port-and-quit flag to controller_debug.py.
1. 👉 #533 Add --detect-port-and-quit flag to controller_debug.py. 👈 **YOU ARE HERE**
1. #534 Add scaling support to trace graph.
1. #535 Set gui_mode last when applying a preset.
1. #536 Add script to run all covent tests in a row.
> Add --detect-port-and-quit flag to controller_debug.py.

- utils/controller_debug.py
<git-pr-chain>
1. Add scaling support to trace graph.
This lets you graph e.g. volume and pressure on the same chart (divide
volume by 10 and it works ok).
1. 👉 #534 Add scaling support to trace graph. 👈 **YOU ARE HERE**
1. #535 Set gui_mode last when applying a preset.
1. #536 Add script to run all covent tests in a row.
> Add scaling support to trace graph.

- controller/lib/core/pinch_valve.cpp
- controller/lib/core/pinch_valve.h
- scripts/pinch_valve_cal.py
I noticed that my pinch valves were leaking when the should have been fully closed.  I adjusted them and rebuilt the linearization table.
I also added the script that I use to generate that table to the scripts directory.
> Minor tweaks to pinch valve calibration

- controller/lib/core/pinch_valve.cpp
<git-pr-chain>
1. Update comment in pinch_valve.cpp
https://github.com/RespiraWorks/VentilatorSoftware/pull/529/files#r440567125
1. 👉 #538 Update comment in pinch_valve.cpp 👈 **YOU ARE HERE**
> Update comment in pinch_valve.cpp

- gui/src/latching_alarm.h
- gui/src/max_pressure_alarm.h
- gui/tests/max_pressure_alarm_test.h
https://github.com/RespiraWorks/VentilatorSoftware/issues/366#issuecomment-644487110
The actual alarm here is unchanged - it is still the "max pressure" alarm which is not what we need (we need a PIP alarm). But this PR changes the latching logic to be what we need.
> Changes alarm latching logic per conversion with Neel and Thomas

- gui/gui.sh
For debug builds, use gui.sh --build --debug
> [GUI] Build release by default on gui.sh

- utils/run_covent_tests.py
<git-pr-chain>
1. Added sys.executable to make run_covent_tests.py run in windows
1. 👉 #547 Added sys.executable to make run_covent_tests.py run in windows 👈 **YOU ARE HERE**
1. #540 Prompt user to adjust test lung during covent tests.
1. #544 Fix calculation of IE ratio for covent tests.
1. #548 Update breath detection algorithm.
> Added sys.executable to make run_covent_tests.py run in windows

- utils/run_covent_tests.py
<git-pr-chain>
1. Prompt user to adjust test lung during covent tests.
1. 👉 #540 Prompt user to adjust test lung during covent tests. 👈 **YOU ARE HERE**
1. #544 Fix calculation of IE ratio for covent tests.
1. #548 Update breath detection algorithm.
> Prompt user to adjust test lung during covent tests.

- gui/README.md
- gui/app/app.pro
- gui/gui.sh
- gui/src/src.pro
> [GUI] Remove QtCharts dependency and update Readme

- gui/app/controls/parameters/PeepParameter.qml
The previous resulted to -1 to 20 with step of 2
> Update PEEP parameters to 5-20 with step of 1

- utils/run_covent_tests.py
<git-pr-chain>
1. Keep fan blowing during covent tests.
...but close the blower valve between tests, so it's less awkward to
fiddle with the test lung compliance.
1. 👉 #572 Keep fan blowing during covent tests. 👈 **YOU ARE HERE**
> Keep fan blowing during covent tests.

- controller/src/main.cpp
<git-pr-chain>
1. Remove outdated comment at the top of main.cpp.
1. 👉 #575 Remove outdated comment at the top of main.cpp. 👈 **YOU ARE HERE**
1. #576 Send flow correction ml/min to GUI.
1. #577 Add patient-disconnected alarm.
1. #578 Nix NO_GUI_DEV_MODE define.
> Remove outdated comment at the top of main.cpp.

- gui/common.pri
- gui/src/alarm_manager.h
- gui/src/patient_detached_alarm.h
- gui/src/src.pro
- gui/tests/patient_detached_alarm_test.h
- gui/tests/tests.pro
- gui/tests/tst_main.cpp
<git-pr-chain>
1. Add patient-disconnected alarm.
The GUI doesn't surface the flow correction value anywhere, so there's
nothing to highlight when this alarm occurs.
1. 👉 #577 Add patient-disconnected alarm. 👈 **YOU ARE HERE**
1. #578 Nix NO_GUI_DEV_MODE define.
> Add patient-disconnected alarm.

- controller/src/main.cpp
<git-pr-chain>
1. Nix NO_GUI_DEV_MODE define.
Good riddance.
1. 👉 #578 Nix NO_GUI_DEV_MODE define. 👈 **YOU ARE HERE**
> Nix NO_GUI_DEV_MODE define.

- controller/README.md
<git-pr-chain>
1. Add graph of controller code to controller/README.md.
Mostly I just want to check this in somewhere because I've included this
graph in our covent submission.
1. 👉 #588 Add graph of controller code to controller/README.md. 👈 **YOU ARE HERE**
> Add graph of controller code to controller/README.md.

- gui/README.md
This information should enable anyone with an rpi to run our latest GUI with little to no additional research, either by building it natively or by using the generated images. Left a couple of TODOs to those who may be more knowledgeable.
> Improve GUI (power) user documentation

- gui/app/app.pro
- gui/app/qml.qrc
This takes care of compilation OOMs.
> Do not embed all the sample data into GUI

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
<git-pr-chain>
1. Add fast and slow average debug vars.
Also rename some existing vars, so everything is consistent.
1. 👉 #590 Add fast and slow average debug vars. 👈 **YOU ARE HERE**
1. #605 Add and run pre-commit forbidding CRLF.
1. #607 Move scripts directory to utils/controller_debug_scripts.
1. #608 Move boards -> controller/build_config.
1. #609 Reformat dates under sample-data.
1. #606 Move dead-link-test into top-level config.
> Add fast and slow average debug vars.

- controller/build_config/stm32_scripts.py
- controller/lib/hal/hal_stm32.cpp
Fixes some link errors caused by the latest pio update
> Fix link errors

- gui/app/controls/parameters/PeepParameter.qml
https://respiraworks.slack.com/archives/C011UMNUWGZ/p1592756403281400
> PEEP should be capitalized

- controller/integration_tests/README.md
- controller/integration_tests/blower_test.h
- controller/integration_tests/buzzer_test.h
- controller/integration_tests/deploy_test.sh
- controller/integration_tests/labjack/ams5915.py
- controller/integration_tests/labjack/posifa.py
- controller/integration_tests/main.cpp
- controller/integration_tests/pinch_valve_test.h
- controller/integration_tests/platformio/README.md
- controller/integration_tests/run_all.sh
- controller/integration_tests/stepper_test.h
- platformio.ini
- test.sh
* POC Labjack script for Posifa flow sensor works
* Integration test deployment script improved
* Integration tests take parameters
* More docs & notes on other redundant sensors we will be working with
> Integration test improvements

- quality-assurance/testing/testing-data/v0.2/2020-06-21-RunForRecord2-AIR-and-OXY/test-README.md
- quality-assurance/testing/testing-data/v0.2/2020-07-01-Control-Tests-AIR-and-OXY/2020-07-01-Control-Tests-AIR/README.md
- quality-assurance/testing/testing-data/v0.2/2020-07-01-Control-Tests-AIR-and-OXY/2020-07-01-Control-Tests-OXY/README.md
- software/controller/README.md
- software/controller/integration_tests/README.md
- software/sample-data/2020-06-21-RunForRecord2-AIR-and-OXY/test-README.md
- software/sample-data/2020-07-01-Control-Tests-AIR-and-OXY/2020-07-01-Control-Tests-AIR/README.md
- software/sample-data/2020-07-01-Control-Tests-AIR-and-OXY/2020-07-01-Control-Tests-OXY/README.md
Controller architecture diagram was broken upon repo restructure. Took the opportunity to update the controller docs more generally.
> Patch controller arch diagram

- .github/ISSUE_TEMPLATE/task.md
Add a checklist of things to do for each new task created in github issues
> Add a checklist of things to do for each new task created in github issues

- README.md
badge for open source
badge for license
custom donate badge
link to wiki
> more badges and gofundme link

- .github/.codecov.yml
- software/common/generated_libs/network_protocol/network_protocol.pb.h
- software/common/generated_libs/network_protocol/network_protocol.proto
- software/common/libs/units/units.h
- software/controller/lib/core/sensors.cpp
- software/controller/lib/core/sensors.h
- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/hal.h
- software/controller/src/main.cpp
- software/controller/test/controller/controller_test.cpp
- software/controller/test/sensor_tests/sensors_test.cpp
- software/controller/test/units/units_test.cpp
Built from @inceptionev's sample branch for o2 sensor.
As I don't have the hardware for this, this will also require testing from someone with the sensor.
TODO: make sure the sensor is properly calibrated : purge with air only, wait 10s before calibration.
> add o2 sensor

- software/gui/app/controls/readings/FiO2Display.qml
- software/gui/src/gui_state_container.h
Needs testing as I don't have the hardware for now.
> Wire fiO2 in placeholder inside GUI

- software/controller/lib/core/controller.cpp
- software/controller/lib/core/controller.h
- software/controller/test/blower_fsm/blower_fsm_test.cpp
- software/controller/test/controller/controller_test.cpp
- software/controller/test/sensor_tests/sensors_test.cpp
Adds simple test cases for the control laws, and the framework to add more complex cases, if we ever need to.
> Improve controller test coverage with test of pressure control laws

- software/controller/lib/core/circular_buffer.h
- software/controller/lib/debug/debug.h
- software/controller/lib/debug/trace.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/test/circ_buff/circ_buff_test.cpp
- software/controller/test/debug/trace_test.cpp
Make the template safe against N<0 and N=0
Enhance existing tests and add tests
Closes #276
> Enhance circular buffer

- manufacturing/3d_printing/AnyCubic_Photon_Fast7_+_tenacious3_profile.cfg
- manufacturing/3d_printing/AnyCubic_Photon_Siraya_fast_profile.cfg
- manufacturing/3d_printing/Elegoo_Mars_70fast_30tenacious_profile.cfg
- manufacturing/3d_printing/README.md
- manufacturing/README.md
Covers these main points:
* printers
* resins
* slicing settings
* guidance on sharing intermediate files
What's missing?
Info on setup with the Elegoo Mars (pro?)
> Added 3d printing guidelines

- manufacturing/enclosed_build/enclosure/CAD/IS 2907 - 1961 - 3 x 14 x 8.6.ipt
- manufacturing/enclosed_build/enclosure/CAD/enclosure_assembly.iam
- manufacturing/enclosed_build/enclosure/CAD/equipment_bracket.ipt
- manufacturing/enclosed_build/enclosure/CAD/ventilator_closure_panel.idw
- manufacturing/enclosed_build/enclosure/CAD/ventilator_closure_panel.ipt
- manufacturing/enclosed_build/enclosure/CAD/ventilator_closure_panel.pdf
- manufacturing/enclosed_build/enclosure/CAD/ventilator_closure_panel.stl
- manufacturing/enclosed_build/enclosure/CAD/ventilator_enclosure.ipt
- manufacturing/enclosed_build/enclosure/README.md
- Following files pertaining to the enclosure were added:
- Ventilator enclosure (.ipt sheet metal file) 
_**Note**: Minor dimensional inaccuracies (due to improper documentation) still persist; resultantly, some holes don't line up and gaps between folded panels may exist_
- Ventilator closure panel (.ipt sheet metal file, .stl file, .dwg & .pdf drawings)
- Equipment bracket (.ipt sheet metal file)
- Work ongoing to improve design to address issues brought up in engineering meetings (i.e. interfering screws when mounting pneumatics tray, better PCB mounting solution, preferably on acrylic as opposed to the display panel etc.)
Note: Contains parts from Inventor Content Center
closes #943
> v0.3 Enclosure migration

- manufacturing/oxygen/README.md
- manufacturing/oxygen/psol/PVQ31-6G-40-01N.ipt
- manufacturing/oxygen/psol/Uflow IBV19M.ipt
- manufacturing/oxygen/psol/barbed_fitting_1-4_x_1-4ntpm.ipt
- manufacturing/oxygen/psol/barbed_fitting_1-4_x_1-8ntpm.ipt
- manufacturing/oxygen/psol/brass_fitting_1-4ntpf_1-8bsptm.ipt
- manufacturing/purchasing_guidelines.md
* Added CAD for
* SMC PSOL
* Uflow PSOL
* BSPT and NTP fittings
* Detailed BOM for PSOL assembly
* More detailed explanation of PSOL installation on Oxygen page
Closes #922
> Adding PSOL CAD and updating assembly docs

- pcb/indicators.sch
Fingers crossed fixed git issues for this
> indicators

- pcb/ui_computer.sch
Comments from prior PR that I need to add edits for:
@dcstraney:
Oh I was talking about the value of the resistors (as in, why they're not all 0) rather than the extra DNP ones.
Just threw in a 10K but yea might as well be 0
@inceptionev
recommend adding decoupling and bulk capacitors to the 5V input power
Ah duh thanks, will do!
did we conclude that we want to move to giving ports generic (GPIO1, GPIO2, PA0, PA1) names at the sub-sheet level? I think we discussed making those assignments at the top sheet level
yea that would be good change to make- will do that
.
> UI Computer

- pcb/fpga.sch
Based on Stephanie's #1014, without the extra files
Changed connector footprint to female rather than male to make pin numberings correct
Added optional place for fuse on 5V input power
> FPGA connections

- pcb/driver_stepper.sch
Fixed power connections
Updated with split/cleaner powerstep01 symbol
Added limit switch filter and connector
Minor cleanups (changed LEDs from diode symbols to LED symbols, renamed ports from arduino-pin to functional names)
Actually, looks like I still need to add an output connector for the stepper motor...
> Stepper driver (2021-02-14)

- design/pneumatic-system/README.md
- design/pneumatic-system/images/flow_control_diagram_current.png
- design/pneumatic-system/images/flow_control_diagram_proposed.png
Adds current and proposed control block diagram to the pneumatic design page.  Partially addresses #883
> Add control diagram to pneumatics page

- software/controller/integration_tests/eeprom_test.h
- software/controller/platformio.ini
> Fix Integration test issues

- software/controller/test/nvparams/nvparams_test.cpp
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #(issue )https://github.com/RespiraWorks/Ventilator/issues/1029 
Updates #(issue)
> update nvparams tests to run independently

- software/controller/integration_tests/eeprom_test.h
- software/controller/lib/core/blower_fsm.cpp
- software/controller/lib/core/controller.cpp
- software/controller/lib/core/controller.h
- software/controller/lib/core/nvparams.cpp
- software/controller/lib/core/sensors.cpp
- software/controller/lib/debug/var_cmd.cpp
- software/controller/lib/debugvars/vars.cpp
- software/controller/lib/debugvars/vars.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/psol.cpp
- software/controller/src/main.cpp
- software/controller/test/debug/interface_test.cpp
- software/controller/test/debug/trace_cmd_test.cpp
- software/controller/test/debug/trace_test.cpp
- software/controller/test/debug/var_cmd_test.cpp
- software/controller/test/debug/vars_test.cpp
- software/utils/debug/README.md
- software/utils/debug/controller_debug.py
- software/utils/debug/debug_cli.py
- software/utils/debug/lib/colors.py
- software/utils/debug/test_data.py
- software/utils/debug/test_scenario.py
- software/utils/debug/test_scenarios/dummy.json
- software/utils/debug/test_scenarios/iso_pressure_tests.csv
- software/utils/debug/test_scenarios/iso_pressure_tests.json
- software/utils/debug/test_scenarios/iso_volume_tests.csv
- software/utils/debug/test_scenarios/iso_volume_tests.json
- software/utils/debug/var_info.py
This finished implementing the additional debug variable features on the Python (client) side of the interface. This consists of:
* more verbose variable info in help output, including enumeration, type, units and format string
* in addition to `get all` we have `get set` and `get read` to filter by access type, with autocomplete
* `help get` only displays writable variables and test metadata only saves writable variables
* fixed PID setting static initialization bug
* checks for debug variable name collision on the Python side
* units defined for most debug variables using proper nomenclature
* alternating color output when retrieving multiple variables
* all override variables renamed `forced_*` instead of `gui_*`
* test data now saves raw settings instead of rendered strings
* traces …
> Better variable handling in debug interface

- .github/pull_request_template.md
- software/common/libs/checksum/checksum.cpp
- software/common/libs/checksum/checksum.h
- software/controller/lib/core/comms.h
- software/controller/lib/core/errors.h
- software/controller/lib/core/nvparams.cpp
- software/controller/lib/core/nvparams.h
- software/controller/lib/debugvars/vars.h
- software/controller/lib/hal/hal.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/platformio.ini
- software/controller/src/main.cpp
- software/controller/test/checksum/checksum_test.cpp
- software/controller/test/nvparams/nvparams_test.cpp
This is a rehash of PR #439 as implemented by @Miceuz 
The original review was complete, but changes to master have caused github to force-closed the PR. The branch as been rebased and this is the new PR for the same content.
Updates #159
> Remove CRC32 implementation

- .github/.codecov.yml
- .github/pull_request_template.md
- software/controller/controller.sh
- software/utils/debug/controller_debug.py
- software/utils/debug/debug_cli.py
- software/utils/rpi_config/bootstrap.sh
- software/utils/rpi_config/update.sh
This addresses a few shortcomings of the debug CLI as revealed in user testing:
* **BUG FIX** `controller.sh` utility script was not CDing into the debug scripts directory before running, thus confusing the script about relative directories, for example test scenarios were not being loaded
* More robust using of portable file path libraries. Possible cause of inability of autocomplete to find test data file names on some platforms -- **needs testing on Windows**
* `set` now also exposes the `force_open` and `force_off` macros as abstracted in lower level interface
* `get` now processes wildcards, for example `get force*` or `get *blow*` or `get *_k?` like in filesystem but not full on regex (no normal humans know how to use this anyway...)
* `env` command now displays some CLI parameters …
> Controller debug CLI improvements

- software/controller/integration_tests/blower_test.h
- software/controller/integration_tests/buzzer_test.h
- software/controller/integration_tests/eeprom_test.h
- software/controller/integration_tests/idle_test.h
- software/controller/integration_tests/pinch_valve_test.h
- software/controller/integration_tests/psol_test.h
- software/controller/integration_tests/stepper_test.h
- software/controller/lib/core/comms.cpp
- software/controller/lib/core/nvparams.cpp
- software/controller/lib/core/pinch_valve.cpp
- software/controller/lib/core/sensors.cpp
- software/controller/lib/debug/interface.cpp
- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/hal.h
- software/controller/lib/hal/hal_mock.cpp
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/stepper.h
- software/controller/lib/hal/system_timer.cpp
- software/controller/lib/hal/system_timer.h
- software/controller/platformio/build_config/auto_firmware_version.py
- software/controller/src/main.cpp
- software/controller/test/blower_fsm/blower_fsm_test.cpp
- software/controller/test/comms/comms_test.cpp
- software/controller/test/controller/controller_test.cpp
- software/controller/test/debug/interface_test.cpp
- software/controller/test/sensor_tests/sensors_test.cpp
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Updates #(issue)
**OR**
Closes #(issue)
> Refactor system timer in HAL

- .circleci/config.yml
- .circleci/gui_tests_Dockerfile
- software/gui/gui.sh
- software/gui/src/alarm_manager.h
- software/gui/src/breath_signals.h
- software/gui/src/chrono.h
- software/gui/src/connected_device.h
- software/gui/src/controller_history.h
- software/gui/src/gui_state_container.cpp
- software/gui/src/gui_state_container.h
- software/gui/src/latching_alarm.h
- software/gui/src/logger.cpp
- software/gui/src/logger.h
- software/gui/src/patient_detached_alarm.h
- software/gui/src/periodic_closure.cpp
- software/gui/src/periodic_closure.h
- software/gui/src/pip_exceeded_alarm.h
- software/gui/src/pip_not_reached_alarm.h
- software/gui/src/respira_connected_device.h
- software/gui/src/simple_clock.h
- software/gui/src/time_series_graph.h
- software/gui/src/time_series_graph_painter.cpp
- software/gui/src/time_series_graph_painter.h
- software/gui/tests/breath_signals_test.h
- software/gui/tests/latching_alarm_test.h
- software/gui/tests/logger_test.h
- software/gui/tests/patient_detached_alarm_test.h
- software/gui/tests/tst_main.cpp
Some general maintenance of GUI build and CI utilities:
* utility script made cleaner based on lessons learned from `controller` and `common`
* install script uses packages that should work with latest Ubuntu, qmake is accessed in a more portable way
* simplified building when without static checks (not using bear)
* circleci uses newer (recomended) image, and asks for more resources to hopefully speed things up
* license headers and modernized include guards for most of the code we wrote ourselves
This is sort of the minimum for what we need to keep sailing, but I don't believe the scripts are robust enough to close the ticket. Will come back for a second round once we achieve some improvement with build tool chain and static check orchestration.
Updates #866
> Improvements to GUI scripts

- software/gui/README.md
Update OS version in GUI readme file
> Update OS version in GUI readme file

- pcb/bringup-software/stm32_test.ino
Adds an STM32duino program that exercises the various hardware functions to assist in hardware bringup and testing (see #1116).
> Add STM32duino test program for exercising hardware

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/task.md
- .github/pull_request_template.md
* Simplifies the wording in the checklist
* Removes some redundant points under software
* Adds checklist for mechanical design
Closes #1247
> Updated ticket and PR templates

- software/utils/rpi_config/README.md
Adding a few instructions to the rpi-config readme as I walk through the process.
**OR**
> Added instructions for the RPi imager setup

- .circleci/config.yml
- software/controller/controller.sh
- software/utils/debug/controller_debug.py
- software/utils/debug/debug_cli.py
- software/utils/debug/debug_funcs.py
- software/utils/debug/unit_test.py
- software/utils/debug/var_info.py
This adds some new functionality to the `set var` command in the debugging interface. Namely
1. High level functions to generate floatarray values
**Linear function**: `set var psol_cal lin(a,b)` sets floatarray to evenly spaced values from a to b
**Identity function**:  `set var psol_cal eigen()` sets floatarray to evenly spaced values from 0 to 1 (wrapper for `lin(0,1)`)
2. Passing raw string as input
`set var "somestring"`
Not tested as none of the settable debug variables are strings yet
Updates #1273
> Adds high level functions to debugging interface

- software/controller/lib/hal/spi_chain.tpp
We no longer block interrupts when the high priority loop queues SPI requests to the stepper motors. In some cases blocking interrupts in this manner lead to us blocking interrupts for longer than the time it takes the debug interface to send a full byte of data, which means the debug interface could lose an incoming byte (condition known as an overrun error).
This fix allows the debug interface to properly handle each received byte in software. A more elegant solution would be to add proper framing to the debug interface, which would allow us to use DMA to handle the reception, requiring less frequent interrupts to run properly (see #1073)
Closes #1298
Tested both by myself on my own pizza build and by @martukas at the CA workshop.
> Fix issue 1298
