- .pre-commit-config.yaml
- README.md
This checks that when you modify some lines of a file, your modifications are clang-formatted.
It doesn't check that the whole file is clang-formatted.
See details at https://github.com/jlebar/pre-commit-hooks
Once we've verified this works for people, I'll do the mass-reformat of all the code.
<pr-train-toc>
👉 #84 (Add clang-format pre-commit.) 👈 **YOU ARE HERE**
#82 (Fix fletcher16 checksum computation.)
#86 (Delete unused .ino files.)
</pr-train-toc>
> Add clang-format pre-commit.

- common/libs/checksum/checksum.cpp
- common/libs/checksum/checksum.h
- controller/src/serialIO.cpp
- controller/test/checksum/checksum_test.cpp
- platformio.ini
In the process of adding the more elaborate tests in this commit, I
found that fletcher16 was not performing well.  Out of the 2^16 random
single bit-flips I tried, 25 had the same checksum.  And one particular
checksum value had ~128/2^16 preimages, i.e. 128 of the 2^16 inputs we
tried all hashed to the same value.
After a bit of investigation, I realized that this was all due to a
subtle C typecasting bug:
*sum1 = ((*sum1) + data[index]) % 255;
The issue is that `data` is a `char`, which may be signed or unsigned
depending on the platform.  If it's signed, then this is bad!
This commit fixes the problem, adds tests that catch the problem
statistically and explicitly, and also simplifies the code and API.
Fixes https://github.com/RespiraWorks/VentilatorSoftware/issues/66.
<pr-train-toc> …
> Fix fletcher16 checksum computation.

- common/include/ventilator_defaults.h
- common/include/ventilator_limits.h
- controller/include/actuators.h
- controller/include/command.h
- controller/include/solenoid.h
- controller/src/actuators.cpp
- controller/src/command.cpp
- controller/src/solenoid.cpp
A bad merge resulted in adding old GPL license headers instead of the
new Apache 2 headers.
cc @lee-matthews
> Fix license headers recently added.

- .travis.yml
- controller/test/checksum/checksum_test.cpp
- platformio.ini
Makes our Travis checks run `platformio run` and `platformio test -e native`.
This required a couple of drive-by fixes: adding pthread for googletest, and fixing a missing include.
> Adds platformio tests to travis.yml

- controller/src/comms.cpp
- platformio.ini
This should let us have nice things, like declaring constants as inline constexpr variables.
> Enables C++17 and fixes some resulting declared-but-undefined warnings

- controller/include/pid.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/lib/hal/hal.h
- controller/src/pid.cpp
- controller/test/sensor_tests/SensorTests.cpp
- platformio.ini
Cleanups:
* Moved pressure constants, together with pressure pin definitions, into `PressureSensors` so the compiler doesn't complain about them being unused
* More type-safe pin ids for analog and PWM pins - hopefully this will help other people be less confused about the fact that e.g. analogWrite is not the opposite of analogRead.
> Enables Wall Werror + a few related cleanups.

- .clang-tidy
- .travis.yml
- controller/include/comms.h
- controller/src/comms.cpp
- platformio.ini
- test.sh
For now I enabled just a single check that had a handful of violations, to demonstrate that this works at all.
The next steps will be to enable more checks, including naming checks. 
This PR is relevant to issue #117 and issue #132 .
> Adds a minimal clang-tidy check

- platformio.ini
- platformio_sanitizers.py
Had to go through a PlatformIO "advanced scripting" script for this, because otherwise it filters out the necessary linker option.
No violations at HEAD, but I confirmed that this works by introducing an out-of-bounds array access in one of the tests and checking that it fails.
> Adds sanitizers to native tests

- controller/include/watchdog.h
- controller/src/command.cpp
- controller/src/main.cpp
- controller/src/watchdog.cpp
- Decrease the watchdog timeout from 8s -> 120ms.  8s seems very long
for a device that is breathing for someone.  Even 120ms seems long,
honestly, but at least not "fatally long".
- Simplify code in watchdog_handler().  wdt_reset() is a single
instruction; I think the old code was a premature optimization and
might even have been slower than this.
- Make watchdog_init() the first thing we do in main().
- Rename watchdog_reboot -> reset_device, which I think is clearer.
- Comments.
I am not sure how this code is going to work when we switch to STM32.
> Tweak watchdog code.

- .clang-tidy
- common/include/packet_types.h
- common/libs/checksum/checksum.cpp
- controller/include/command.h
- controller/lib/core/alarm.cpp
- controller/lib/core/alarm.h
- controller/lib/core/parameters.h
- controller/lib/core/sensors.cpp
- controller/lib/core/solenoid.cpp
- controller/lib/hal/hal.h
- controller/src/command.cpp
- controller/src/comms.cpp
- controller/src/pid.cpp
- controller/src/watchdog.cpp
- controller/test/checksum/checksum_test.cpp
- controller/test/sensor_tests/SensorTests.cpp
- test.sh
Obtained by running clang-tidy with all checks enabled and going through them by hand: ones that yielded either a perceptible improvement in readability or caught an actual bug (they **did** catch a couple of actual bugs) stayed enabled, ones that didn't (i.e. were more likely to annoy people than help), are disabled. We'll probably need to iterate on this more as we write more code.
> Enables some clang-tidy checks and fixes violations

- platformio.ini
- platformio_sanitizers.py
Tried to resurrect msan on Linux + clang but even on Martin's machine with Linux and clang, pio still chose gcc. So maybe it's moot - let's just resurrect the basic sanitizers.
> Resurrect sanitizers without msan

- .clang-tidy
- .gitignore
- .ycm_extra_conf.py
Had to blacklist an additional check in .clang-tidy.  For whatever
reason, YCM was running clang-tidy (cool!) and telling me to change a
bunch of functions to use trailing return types (...not cool?).
> Add .ycm_extra_conf.py, making ycm work!

- test.sh
platformio has released https://bintray.com/platformio/dl-packages/tool-clangtidy/1.100000.0 leading to a bunch of new errors: https://travis-ci.com/github/RespiraWorks/VentilatorSoftware/builds/162016868#L658
Temporarily disabling clang-tidy to stop the bleeding.
The next action would be to, in a single PR:
- Pin version 1.10 (it is cross-platform and can be safely pinned) so we don't have surprise updates in the future
- Re-enable
- Fix the errors
> Temporarily disables clang-tidy

- gui/ControlPanel.qml
- gui/ScopeView.qml
- gui/main.qml
Downgrade required QML module versions to match what is included on Raspbian. Fixes #81
> Downgrade required QML version to match what is included on raspbian

- .ycm_extra_conf.py
<git-pr-chain>
1. Set explicit cwd in .ycm_extra_conf.py.
I don't understand what YCM is doing, but it seems like the
.ycm_extra_conf.py is invoked from different working directories, but
YCM expects the include paths always to be relative to the script's
directory.
1. 👉 #178 Set explicit cwd in .ycm_extra_conf.py 👈 **YOU ARE HERE**
1. #172 Cosmetic and functional improvements to pid.cpp
1. #180 Simplify sensor calibration routine.
> Set explicit cwd in .ycm_extra_conf.py

- controller/include/pid.h
- controller/lib/hal/hal.h
- controller/src/pid.cpp
<git-pr-chain>
1. Cosmetic tweaks to PID code.
1. Make PID functional with current design.
- Switch patient pressure sensor to pin A5.
- Add constants to HAL for PWM pins.
- Switch blower speed to pin PWM 6.
- Set the blower pin to output mode, otherwise we can write to it all
we want, but nothing's gonna happen.
I think it might be better to abstract some of the low-level "pins"
logic into HAL, but this is a first step.
Fixes https://github.com/RespiraWorks/VentilatorSoftware/issues/17
1. HAL-ify pid.cpp.
Add and use overload for Hal.setDigitalPinMode.
1. Update comments per review.
1. 👉 #172 Cosmetic and functional improvements to pid.cpp 👈 **YOU ARE HERE**
1. #180 Simplify sensor calibration routine.
1. #183 Take higher-level args in HAL::analogRead().
> Cosmetic and functional improvements to pid.cpp

- controller/include/pid.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/lib/hal/hal.h
- controller/src/pid.cpp
- controller/test/sensor_tests/SensorTests.cpp
<git-pr-chain>
1. Take higher-level args in HAL::analogRead().
Instead of analogRead(AnalogPinId::HAL_A0), we now do
analogRead(AnalogPin::PATIENT_PRESSURE).
This way the pinout of the STM32 doesn't have to be identical to that of
the Arduino.  I also think it's just easier to follow.
It's a TODO to adopt this same strategy for everything else in HAL.
I also made the sensor code higher level in the same way.  Instead of
returning the raw pressure for each of the three sensors, we now return
the absolute pressure for the one sensor that reads that, and the
computed volumetric flow for the two sensors that (indirectly) measure
this.
Among other things, this makes it impossible to write the bug that I
tried to introduce in
https://github.com/RespiraWorks/VentilatorSoftware/pull/173.
1. 👉 …
> Take higher-level args in HAL::analogRead().

- controller/lib/core/sensors.cpp
- controller/lib/hal/hal.h
- controller/test/sensor_tests/SensorTests.cpp
<git-pr-chain>
1. Clarify that we're using MPXV5004DP pressure sensors everywhere.
Previously we were using the V7002 for some of our sensors.
No code changes are needed -- and we can actually test this! -- because
the only difference between the two from our perspective is that they
give different voltages for zero pressure.  Our code dynamically finds
the zero value *anyway*, so it doesn't make a difference.
I'm still looking for the canonical place that will list exactly what
parts we're using, etc.  We'll be able to link to that from HAL once we
have it.
1. 👉 #192 Clarify that we're using MPXV5004DP pressure sensors everywhere. 👈 **YOU ARE HERE**
1. #188 Blacklist readability-convert-member-functions-to-static clang-tidy check.
1. #189 "Semantically-type" output pins.
1. #190 Clarify …
> Clarify that we're using MPXV5004DP pressure sensors everywhere.

- .clang-tidy
<git-pr-chain>
1. Blacklist readability-convert-member-functions-to-static clang-tidy check.
YCM was warning about this in HAL, where it was noisy.
1. 👉 #188 Blacklist readability-convert-member-functions-to-static clang-tidy check. 👈 **YOU ARE HERE**
1. #189 "Semantically-type" output pins.
1. #190 Clarify that HAL is not a mock.
> Blacklist readability-convert-member-functions-to-static clang-tidy check.

- controller/lib/core/control.cpp
- controller/lib/core/control.h
- controller/lib/core/sensors.cpp
- controller/lib/core/solenoid.cpp
- controller/lib/hal/hal.h
<git-pr-chain>
1. "Semantically-type" output pins.
Instead of telling HAL to write to "pin X", we now tell HAL to write to
the BLOWER/SOLENOID pin.
This consolidates all of the "device X is attached to pin Y" logic into
HAL, so that we can handle a different pinout on e.g. STM32.
It also consolidates the setting of pins to OUTPUT into HAL.  We had a
bug a few days ago where we were forgetting to set the blower to OUTPUT.
But now HAL "owns" the notion that this pin is an output pin, so can
reasonably do this for us, in a consolidated place.
Also strongly-type the difference between "binary pins" that are always
either high or low (e.g. our solenoid) and pins that we pulse-width
modulate.  Of course any pin we PWM could also be set to all-high or
all-low, but in practice we treat them …
> "Semantically-type" output pins.

- controller/lib/core/control.cpp
<git-pr-chain>
1. Fix ODR violation on map() function.
It's an ODR violation for us to define ::map function and also link
against Arduino code, which defines the same function.
`pio run -e nucleo` catches this and thankfully raises an error.  (ODR
violations don't always raise an error.)
Making it static doesn't work, it's still a conflict (though now `pio
run`) still catches it.  Rename the function.
1. 👉 #198 Fix ODR violation on map() function. 👈 **YOU ARE HERE**
1. #193 Simplify blower PID state machine.
1. #194 Disable modernize-use-default-member-init clang-tidy warning
1. #195 Rename algorithm/alg -> stl/algorithm.h.
1. #197 Remove some unused options in network_protocol.proto.
1. #202 Blacklist -misc-non-private-member-variables-in-classes …
> Fix ODR violation on map() function.

- .clang-tidy
<git-pr-chain>
1. Disable modernize-use-default-member-init clang-tidy warning
This was complaining about
enum class E {
X,
Y
};
class Foo {
private:
E val = E::X;
};
It suggested instead that I write it as `E val{};`, which seems far
worse to me.
1. 👉 #194 Disable modernize-use-default-member-init clang-tidy warning 👈 **YOU ARE HERE**
1. #195 Rename algorithm/alg -> stl/algorithm.h.
1. #197 Remove some unused options in network_protocol.proto.
1. #202 Blacklist -misc-non-private-member-variables-in-classes clang-tidy check.
> Disable modernize-use-default-member-init clang-tidy warning

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/test/comms/comms_test.cpp
<git-pr-chain>
1. Remove some unused options in network_protocol.proto.
- Remove FiO2 control.  Ethan said that he anticipates FiO2 will be
controlled externally from the ventilator.
- Remove PRESSURE_ASSIST / PRESSURE_SUPPORT ventilation modes.
I am writing code that wants to switch() on ventilator modes, and
getting rid of the unused modes means the switch() can cover all modes
without a `default` case.  That way when we add a new mode, we'll get
a compile error showing everything we have to change.
1. 👉 #197 Remove some unused options in network_protocol.proto. 👈 **YOU ARE HERE**
1. #202 Blacklist -misc-non-private-member-variables-in-classes clang-tidy check. …
> Remove some unused options in network_protocol.proto.

- .clang-tidy
<git-pr-chain>
1. Blacklist -misc-non-private-member-variables-in-classes clang-tidy check.
This literally tries to enforce that every variable be private;
protected is not allowed period.
I sort of think this proves that we should go to a whitelist for
clang-tidy checks.
1. 👉 #202 Blacklist -misc-non-private-member-variables-in-classes clang-tidy check. 👈 **YOU ARE HERE**
> Blacklist -misc-non-private-member-variables-in-classes clang-tidy check.

- controller/lib/stl/new.h
<git-pr-chain>
1. Add stl/new.h.
Polyfills part of <new> so that placement new is available even though
we don't have a C++ STL.
Unfortunately no tests because we can't run tests on Arduino and this
header has to be a nop on the native platform (where we do have <new>,
and it gets pulled in and conflicts with the header).
1. 👉 #196 Add stl/new.h. 👈 **YOU ARE HERE**
> Add stl/new.h.

- gui/ProjectVentilatorGUI.pro
- gui/ScopeView.qml
- gui/chrono.h
- gui/connected_device.h
- gui/controller_history.h
- gui/gui_state_container.h
- gui/main.cpp
- gui/periodic_closure.cpp
- gui/periodic_closure.h
This is part of issue #4 .
- Tweaks the QT project file to make nanopb and the generated protocol headers available
- Introduces a `ConnectedDevice` abstraction for exchanging state with a device. In this PR we add a fake, but @Miceuz , as a follow up, can make an implementation that uses the serial port and talks to the real controller.
- Introduces `ControllerHistory` that keeps track of the last N seconds of `ControllerStatus` protos
- Introduces `PeriodicClosure` that runs a lambda on a schedule, so we can e.g. get the next controller status every 10ms (I don't know what is an appropriate period).
- Introduces `GuiStateContainer` which will contain, in a thread-safe way, everything that the UI elements may need to read or write. It will be up to the UI to bind itself to components of …
> Introduces GUI plumbing for keeping track of controller history.

- controller/lib/core/blower_pid.cpp
<git-pr-chain>
1. Explicitly set the output limits in our blower PID.
No functional change; the default output limits were already 0-255.
1. 👉 #216 Explicitly set the output limits in our blower PID. 👈 **YOU ARE HERE**
1. #217 Control the solenoid from the Blower FSM.
1. #218 Add NO_GUI_DEV_MODE, for running the controller without a GUI.
> Explicitly set the output limits in our blower PID.

- gui/ProjectVentilatorGUI.pro
- gui/controller_history.h
- gui/gui_state_container.h
- gui/main.cpp
- gui/main.qml
Removes alarms (because we don't support them yet, so for now it's just more code to modify) and binds params directly to GuiStateContainer, getting rid of GuiStateInterface. 
I also used QT's property mechanism instead of inc/dec functions.
> Removes alarms and binds params directly to GuiStateContainer

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/blower_pid.cpp
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Turn off fan immediately when state is switched to OFF.
Rather than turning off the fan by setting the setpoint to 0 (and
waiting for PID to spin down to approximately 0), shut off the fan
entirely, do not pass go, etc.
1. 👉 #230 Turn off fan immediately when state is switched to OFF. 👈 **YOU ARE HERE**
1. #231 Fix 16-bit overflow in Hal timer code.
1. #232 First pass at tidal volume measurement.
1. #233 Re-tune PID.
1. #234 Change default params in DEV_MODE_comms_handler.
> Turn off fan immediately when state is switched to OFF.

- common/libs/units/units.h
- controller/lib/hal/hal.h
<git-pr-chain>
1. Fix 16-bit overflow in Hal timer code.
`int` on Arduino is 16 bits wide, and 2^15ms is only about 30 seconds.
Therefore a signed int overflows quite frequently!
Fixed to be int64_t, as it should be.
Fixes #224.
1. 👉 #231 Fix 16-bit overflow in Hal timer code. 👈 **YOU ARE HERE**
1. #232 First pass at tidal volume measurement.
1. #233 Re-tune PID.
1. #234 Change default params in DEV_MODE_comms_handler.
> Fix 16-bit overflow in Hal timer code.

- controller/lib/core/blower_pid.cpp
<git-pr-chain>
1. Re-tune PID.
Edwin added an output constriction to the device -- i.e. he reduced the
diameter of the exhaust tube.  We then needed to re-tune PID.
We also needed to re-tune because my previous experiments were done at a
high PIP and PEEP, and this was causing the blower to max out.
1. 👉 #233 Re-tune PID. 👈 **YOU ARE HERE**
1. #234 Change default params in DEV_MODE_comms_handler.
> Re-tune PID.

- controller/lib/core/alarm.cpp
- controller/lib/core/blower_pid.cpp
- controller/lib/core/comms.cpp
- controller/lib/core/sensors.cpp
- controller/lib/hal/hal.h
- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
- controller/test/comms/comms_test.cpp
<git-pr-chain>
1. Fix up Time/Duration handling.
- Make Time an int64 and handle clock overflow.
- Remove weakly-typed Hal::millis() and Hal::delay(int32) functions.
- Fix up code so that it all uses strongly-typed functions.
The main motivation is handling timer overflow properly.  As we saw in
https://github.com/RespiraWorks/VentilatorSoftware/issues/224, overflow
can be very serious!
1. 👉 #238 Fix up Time/Duration handling. 👈 **YOU ARE HERE**
> Fix up Time/Duration handling.

- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/test/pid_lib/pid_test.cpp
Functional changes I made to the PID library:
1. made it run when now > next multiple of sample time, instead of now > time of last call + sample time, in order to better approximate what we would get with a RTOS
2. made the integral/derivative use dt = now - "time of last call", instead of fixed sample time, as I said in the linked issue, if we want to have even better math, we could have the sensors timestamp their data and use dt = timestamp of current data - timestamp of previous data
3. added derivative on error mode, to make it possible to use like a regular PID, probably not useful, as per discussion with Edwin.
For an illustration of what points 1 and 2 do, see https://docs.google.com/presentation/d/19FcO7h6YPZx7-ondiH7kgkY8SAafKVgVLtLYb_zi43k/edit?usp=sharing
> add pid library unit tests and fix issue seen with those unit tests

- .circleci/config.yml
- gui/Dockerfile
- gui/test.sh
This issue fix the failing gui-build-image CircleCI build, see #251 
Note, the branch is named incorrectly as issue 252, my bad.
https://app.circleci.com/pipelines/github/RespiraWorks/VentilatorSoftware/614/workflows/7a9edc26-9499-48c2-b03a-2ce509ebeca4
> Include common code in gui Docker build context, fixes #251

- gui/rpi-image/rpi-primer.yml
This change modifies the RPi image so that when auto-login is enabled, Openbox will be run as the `pi` user. This makes interaction between Docker and X11 a little easier, and will be necessary to tighten up the system permissions in production.
> Launch openbox as pi user (assuming auto login enabled)

- common/libs/units/units.h
- controller/lib/core/blower_pid.cpp
- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/lib/stl/algorithm.h
- controller/test/pid_lib/pid_test.cpp
Brings it in accordance with common best practices for C++ APIs, implementation and naming / style:
- Gets rid of some useless, redundant and error-prone APIs, e.g. the "manual" mode in which the PID does nothing at all (just ignore its output, if you don't want it to do anything!), and ways to change settings that shouldn't be changed
- Passes inputs explicitly to Compute() instead of requiring the caller to store them in (most likely) a static variable
- Uses strongly typed enums for configuration modes instead of ints and (accidentally inverted) booleans
- Consistent naming
The benefit of this as a whole is - less error-prone, less intimidatingly-looking for others who might have to make changes, less "broken windows" in our code.
No functional changes.
Still remains to refactor tests …
> Modernizes the PID library

- controller/lib/hal/hal.h
- platformio.ini
- test.sh
Nucleo (STM32 with Arduino SDK) is not going to be used because instead we're going to use bare STM32 that @sglow added in #225 .
> Removes nucleo env but makes test.sh run both stm32 and uno, until uno is gone

- common/libs/checksum/checksum.cpp
- common/libs/checksum/checksum.h
- common/libs/units/units.h
- controller/lib/core/alarm.cpp
- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_pid.cpp
- controller/lib/core/comms.cpp
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- controller/test/blower_fsm/blower_fsm_test.cpp
- controller/test/checksum/checksum_test.cpp
- controller/test/comms/comms_test.cpp
- controller/test/pid_lib/pid_test.cpp
- controller/test/units/units_test.cpp
- platformio.ini
A couple really scary bugs:
- alarm.cpp used an uint32 timestamp instead of uint64 (or time)
- comms.cpp would probably have data corruption if transmitting or receiving more than 128 bytes
- sensors.cpp had float->int precision loss during calibration
> Enables -Wconversion and fixes violations, including several serious bugs

- common/libs/units/units.h
- controller/lib/core/actuators.cpp
- controller/lib/core/actuators.h
- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/blower_pid.cpp
- controller/lib/core/blower_pid.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
- controller/test/units/units_test.cpp
This PR should allow integration of the controller to Modelica models for testing.
What it does is:
- refactor code to read sensors inputs prior to any controls computation and execute commands after actual computation
- replace all the calls to Hal.now() in controls computations by a reference to the time of the call. This is considered a good thing for the PID as it makes "now" be closer to the time when measurements were made. Could be considered bad for blower_fsm, as the commands might take one more cycle to be executed, and in blower fsm, this might make 1 breath difference.
- create a class that encapsulates all controls computation (this class is interface with Modellica)
To do but I feel overwhelmed: include ActuatorsState to ControllerStatus in nanopb.
Part of #263 , but doesn't …
> issue263: refactor computation to allow integration in Modellica

- controller/lib/core/circular_buffer.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
- controller/test/circ_buff/circ_buff_test.cpp
This is a simple change to close issue #268.  It just moves the circular buffer implementation from the HAL to the core library and adds some unit tests for the buffer.
Fixes #268
> Issue 268 circular buffer

- controller/lib/hal/hal.h
- platformio.ini
- test.sh
<git-pr-chain>
1. Revert "Removes nucleo env but makes test.sh run both stm32 and uno, until uno is gone"
This reverts commit 6392c1cba737030a7ddcc62ca4757682bc9dd614.
It turns out that we're not quite ready to get rid of the "nucleo"
target yet.  The Arduino APIs are useful for communicating with the
STM32 dev board until:
- Our HAL knows how to talk over the STM's USB serial output.
- Our HAL knows works with L452RE-P's pinout -- or otherwise we get rid
of all the -P boards.
This is a clean revert.  In a separate commit I will restore the
desirable changes to test.sh.
1. Update test.sh to run on all relevant platforms.
Currently relevant platforms are uno, stm32, and nucleo.
1. 👉 #278 Revert "Removes nucleo env but makes test.sh run both stm32 and uno, until uno is gone" 👈 **YOU ARE …
> Revert "Removes nucleo env but makes test.sh run both stm32 and uno, until uno is gone"

- .ycm_extra_conf.py
<git-pr-chain>
1. Update .ycm_extra_conf to use STM32 flags.
Now that Uno is gone, we shouldn't build with Uno flags.
1. 👉 #281 Update .ycm_extra_conf to use STM32 flags. 👈 **YOU ARE HERE**
1. #282 Delete support for Arduino Uno.
1. #283 Use std::variant in blower_fsm.h.
1. #284 Remove stl::min/max/clamp.
1. #296 Tweak …
> Update .ycm_extra_conf to use STM32 flags.

- controller/lib/hal/hal.h
- platformio.ini
- test.sh
<git-pr-chain>
1. Delete support for Arduino Uno.
Goodbye, fair chip.
1. 👉 #282 Delete support for Arduino Uno. 👈 **YOU ARE HERE**
1. #283 Use std::variant in blower_fsm.h.
1. #284 Remove stl::min/max/clamp.
> Delete support for Arduino Uno.

- controller/lib/core/sprintf.cpp
<git-pr-chain>
1. Fix sprintf build on my machine.
- isnanf/isinff doesn't exist for me, and afaict they're not standard C
functions. https://en.cppreference.com/w/c/numeric/math/isnan
https://en.cppreference.com/w/c/numeric/math/isinf
- I get a warning about `if (av)` when `av` is a float.  Made explicit.
1. 👉 #299 Fix sprintf build on my machine. 👈 **YOU ARE HERE**
1. #284 Remove stl::min/max/clamp.
1. #293 Fix trailing whitespace in a README.md …
> Fix sprintf build on my machine.

- controller/lib/core/comms.cpp
- controller/lib/hal/hal.h
- controller/lib/pid/pid.cpp
- controller/lib/stl/algorithm.h
<git-pr-chain>
1. Remove stl::min/max/clamp.
Use std::min/max/clamp now that we always have a C++ standard library
available.
Unfortunately we can't remove our algorithm.h shim quite yet; see
comment in the header.
1. 👉 #284 Remove stl::min/max/clamp. 👈 **YOU ARE HERE**
1. #294 …
> Remove stl::min/max/clamp.

- controller/lib/hal/hal_stm32.cpp
- controller/lib/hal/hal_stm32.h
<git-pr-chain>
1. C++17 tweaks to hal_stm32.{h,cpp}
The most significant is using the IIFE trick for switch statements that
"return" a value.  This is safer because e.g. when you're returning two
variables, you *can't* forget to assign one of them.
No functional change.
1. 👉 #295 C++17 tweaks to hal_stm32.{h,cpp} 👈 **YOU ARE HERE**
> C++17 tweaks to hal_stm32.{h,cpp}

- platformio.ini
<git-pr-chain>
1. Pass -Wno-sign-conversion to gcc.
I believe this is no functional change: GCC's docs claim that
sign-conversion is enabled by -Wconversion only for C code.
1. 👉 #297 Pass -Wno-sign-conversion to gcc. 👈 **YOU ARE HERE**
> Pass -Wno-sign-conversion to gcc.

- controller/lib/core/sensors.cpp
- controller/test/sensor_tests/sensors_test.cpp
The tolerance it was using (~0.005) was larger than the value being compared (~0.001).
> Fix sensors_test to use correct comparison tolerance

- common/generated_libs/network_protocol/network_protocol.pb.c
- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/lib/core/controller.cpp
- controller/lib/core/sensors.cpp
- controller/src/main.cpp
- controller/test/comms/comms_test.cpp
- controller/test/sensor_tests/sensors_test.cpp
- gui/gui_state_container.cpp
- gui/gui_state_container.h
- gui/main.cpp
<git-pr-chain>
1. Tweak SensorReadings proto.
- Rename pressure_cm_h2o -> patient_pressure_cm_h2o
- Add {inflow,outflow}_pressure_cm_h2o.  These values are primarily
useful for debugging, but it's fine to send them everywhere.
- Tweak the DEV_MODE serial printf.  Now it's a series of printfs, so
that it's easy to comment one out.
Volume is commented out in the printf because without something to fix
the linear component of the volume, it quickly overwhelms the other
values in the graph, rendering everything else out-of-scale.
1. 👉 #311 Tweak SensorReadings proto. 👈 **YOU ARE HERE**
1. #312 Make Hal::analog{Read,Write} use Voltages.
1. #313 Add BlockInterrupts RAII class.
> Tweak SensorReadings proto.

- controller/lib/core/actuators.cpp
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. Make Hal::analog{Read,Write} use Voltages.
Instead of using raw numbers in the range 0-1024 and 0-255.
This lets us take advantage of the additional ADC and PWM resolution in
STM32, but it's also just a nicer and more strongly-typed API.
1. Nix HAL_CONSTANT.
This was a workaround for #defines in the Arduino headers, which we are
rid of.
1. 👉 #312 Make Hal::analog{Read,Write} use Voltages. 👈 **YOU ARE HERE**
1. #313 Add BlockInterrupts RAII class.
> Make Hal::analog{Read,Write} use Voltages.

- controller/lib/core/circular_buffer.h
- controller/lib/hal/hal.h
- controller/lib/hal/hal_stm32.cpp
<git-pr-chain>
1. Add BlockInterrupts RAII class.
This is a safer C++/RAII way to block and restore interrupts.
This slightly expands the critical section in FullCt().  I could reduce
it if that's a problem.
Also renames IntEnable/IntDisable to enableInterrupts() and
disableInterrupts().  These names make it so that it's unnecessary to
have comments explaining what the functions do.  Also our method names
start with lower case letters (apparently).
1. 👉 #313 Add BlockInterrupts RAII class. 👈 **YOU ARE HERE**
> Add BlockInterrupts RAII class.

- common/libs/units/units.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/test/sensor_tests/sensors_test.cpp
- controller/test/units/units_test.cpp
Fix a bug seen while adding unit tests to the sensors, while I am not 100% satisfied with the tests, this fix cannot really wait.
Per reviewers demand, finally added the tests I was working on.
> Restore memory of last_flow in TVIntegrator::GetFlow() + simplify volume update

- .pre-commit-config.yaml
Enforces that C++ files have to be named `like_this`. At the moment there are no violations but I checked that adding a WronglyNamed.cpp file triggers the check.
> Adds a first code style check: file naming

- controller/lib/hal/hal_stm32_regs.h
- controller/lib/hal/uart_dma.cpp
<git-pr-chain>
1. Bitfield-ify UART timeout field.
1. #337 Move sprintf.{h,cpp} to new debug library.
1. #338 Fix Flash/RAM size in STM32 board config.
1. 👉 #339 Bitfield-ify UART timeout field. 👈 **YOU ARE HERE**
1. #340 Bitfield-ify UART `request` field.
1. #341 Bitfield-ify UART status register.
> Bitfield-ify UART timeout field.

- boards/custom_stm32.json
<git-pr-chain>
1. Fix Flash/RAM size in STM32 board config.
See https://en.wikipedia.org/wiki/STM32, which lists the specs better
than anything else I have found.
Patch by sglow@ in issue_301_debug_interface.
1. 👉 #338 Fix Flash/RAM size in STM32 board config. 👈 **YOU ARE HERE**
1. #347 Bitfield-ify UART timeout field.
1. #340 Bitfield-ify UART `request` field.
1. #348 Bitfield-ify UART status register.
> Fix Flash/RAM size in STM32 board config.

- controller/lib/hal/uart_dma.cpp
- controller/lib/hal/uart_dma.h
<git-pr-chain>
1. C++ nits in uart_dma.
- "inline" should only be used on functions in header files.  In modern
C and C++, it is a directive to the linker that a function should be
deduplicated.  See https://en.cppreference.com/w/cpp/language/inline,
"The original intent of the inline keyword..."
Functions which are "private" to .cpp files should be marked static.
This prevents an ODR violation (undefined behavior) which would occur
if a different cpp file defined a function of the same name.
- Marked a one-arg constructor as "explicit".  Most one-arg constructors
should be explicit; see https://en.cppreference.com/w/cpp/language/explicit.
- Got rid of `const uint32_t` in function declaration.  This is a nit,
and a weird corner-case in C++.  Behold.
The intent of this `const` is to …
> C++ nits in uart_dma.

- controller/lib/debug/debug.cpp
- controller/lib/debug/pb_read.cpp
- controller/lib/debug/pb_read.h
- controller/lib/debug/peek.cpp
- controller/lib/debug/peek.h
- controller/lib/debug/poke.cpp
- controller/lib/debug/poke.h
- controller/lib/debug/trace.cpp
- controller/lib/debug/trace.h
- controller/lib/debug/vars.cpp
- controller/lib/debug/vars.h
This includes one bug (= instead of ==) and something that is most likely undefined behavior but somehow worked: all the debug cmds were declared as static variables of type "FooCmd" in their respective sources, but then as "extern DebugCmd" (different type) in debug.cpp.
This PR contains no code changes except to the body of one function in debug.cpp where the extern vars were declared. Everything else is just moving code around verbatim.
> Makes ./test.sh pass with clang.

- common/libs/units/units.h
- controller/lib/core/sensors.cpp
- controller/test/units/units_test.cpp
+= and -= operators for ArithScalar
New ModuleScalar template for averaging/applying a multiplying factor (e.g calibration of flow?) right now only for flow and volume
Define Volume = VolumetricFlow\*Duration = Duration\*VolumetricFlow and VolumetricFlow = Volume/Duration
Thought those might come in handy to allow us some more advanced calculations, especially for flow and volume, as it looks like we are going to have to get some correcting factors somewhere, and constantly calling those unit(something.unit()*CORRECTION) is going to get harder and harder to follow.
Also added Time+=Duration and Time-=Duration unit tests, which looked to be missing.
> Add functionality to units

- controller/lib/debug/debug.h
- controller/lib/debug/trace.cpp
- controller/lib/debug/var_cmd.cpp
- controller/lib/debug/vars.cpp
- controller/lib/debug/vars.h
- controller/lib/hal/hal.h
- controller/test/debug/var_cmd_test.cpp
- controller/test/debug/vars_test.cpp
They are always 32-bit, at least for now. This way they don't need to do error checking - that belongs in the higher-level comms protocol code; and the code generally becomes more concise.
Also renames a few functions/variables to follow our more common style and abbreviates the repetitive constructors.
> Changes debug vars to be adapters over uint32_t and adds basic tests

- gui/rpi-image/rpi-primer.yml
Added steps to cache the latest respiraworks/gui docker image from docker hub into the raspbian image and spin it up on boot.
> Cache latest gui docker image & spin up on boot

- boards/stm32_scripts.py
- platformio.ini
This lets us use `static` variables inside of functions with types that
have nontrivial initializers.  Without this, you'll get a mysterious
error of the form
```
sp/hard/libnosys.a(sbrk.o): In function `_sbrk':
sbrk.c:(.text._sbrk+0x18): undefined reference to `end'
```
which indicates that something is trying to call malloc.
> Pass -fno-threadsafe-statics.

- controller/lib/hal/stepper.h
- platformio.ini
…to avoid compiler optimizing out busy wait in StepMotor::SenCmd. Fixes #393
> Declare cmd_ptr_ a volatile pointer to volatile data 

- .pre-commit-config.yaml
<git-pr-chain>
1. Update jlebar/pre-commit-hooks repo.
Fixes Windows, and fixes cases where the user's tempdir is a different
filesystem than their home directory.
1. 👉 #398 Update jlebar/pre-commit-hooks repo. 👈 **YOU ARE HERE**
> Update jlebar/pre-commit-hooks repo.

- gui/FpsItem.qml
- gui/kms.json
- gui/main.qml
- gui/qml.qrc
- gui/run_eglfs.sh
This script run_eglfs.sh is added alongside a kms configuration
file to force egl to run in a specific resolution/refresh_rate.
The script also enables some Qt debugging information to make it
easy to troubleshoot eventual issues with graphics
Also added a small fps counter element so we can keep track of
performance degradations.
This script assumes you are trying to run the GUI **without** X11 started.
> [GUI] Add script to run gui on eglfs 1920 x 1080 @ 60 mode

- common/libs/proto_traits/proto_traits.cpp
- common/libs/proto_traits/proto_traits.h
- controller/test/proto_traits/proto_traits_test.cpp
<git-pr-chain>
1. Add ProtoTraits traits class.
This lets you generically access e.g. MaxSize for T, where T is one of
our protos.
Meant to be used in https://github.com/RespiraWorks/VentilatorSoftware/pull/346.
1. 👉 #402 Add ProtoTraits traits class. 👈 **YOU ARE HERE**
1. #410 Clean up build flags.
1. #411 Build with -fno-exceptions.
1. #412 Build with -fno-rtti.
1. #413 Add an implementation of __cxa_pure_virtual.
> Add ProtoTraits traits class.

- platformio.ini
<git-pr-chain>
1. Clean up build flags.
- Make stm32_build_flags variable, shared between the two STM32 builds.
This causes `-e stm32-test` to run with -fstrict-volatile.
- Filter src_test out of `native` build, so `pio run -e native` now
doesn't try to build src_test.  (This isn't a standard command,
usually we do `pio test -e native`.)
1. 👉 #410 Clean up build flags. 👈 **YOU ARE HERE**
1. #411 Build with -fno-exceptions.
1. #412 Build with -fno-rtti.
1. #413 Add an implementation of __cxa_pure_virtual.
> Clean up build flags.

- controller/lib/debug/vars.h
- controller/src/pure_virtual.cpp
<git-pr-chain>
1. Add an implementation of __cxa_pure_virtual.
This (together with patches earlier in the queue) allows us to use pure
virtual functions, yay.
Also use them in vars.h.
1. 👉 #413 Add an implementation of __cxa_pure_virtual. 👈 **YOU ARE HERE**
> Add an implementation of __cxa_pure_virtual.

- controller/integration_tests/blower_test.h
- controller/integration_tests/main.cpp
- controller/integration_tests/pinch_valve_test.h
- controller/integration_tests/pure_virtual.cpp
- controller/integration_tests/solenoid_test.h
- controller/integration_tests/stepper_test.h
- platformio.ini
- test.sh
These look like primitive demo programs you might get with a driver library. That they are. And hopefully they can be examples to some of the hardware team for acclimating to our HAL.
But they are also test cases that we can use to confirm our software-hardware stacks behave the same from prototype to prototype. Each can be deployed to the controller and effects are easy enough to confirm visually. This we can start taking advantage of ASAP among everyone with some semblance of pizza.
The next immediate plans for this code are:
* spin up Jenkins server (or something similar) to deploy each test to a hardware unit, make this part of CI
* upon receiving some additional sensor hardware, automate confirmation of actuator work by either reading voltages or measuring some downstream effects …
> Basic vertical integration tests

- controller/lib/core/actuators.cpp
- controller/lib/core/pinch_valve.cpp
- controller/lib/core/pinch_valve.h
- controller/lib/hal/stepper.cpp
I made a couple changes to the pinch valves as I work toward closing the loop using these.
1) I changed the homing method so that they get homed using a state machine from the high priority task rather then on startup.  This has several benefits; it allows the watchdog timer to start earlier.  It allows the pinch valves to be disabled when the ventilator is not in use and it allows multiple valves to be homed at the same time when they are enabled.
2) I added a table to roughly linearize the flow sensors so when you command 20% you should get roughly 20% of the full flow rate.  Previously you just got 20% of the pinch valve position.
> Issue 418 pinch valve linearize

- gui/ModeSelectionPopup.qml
- gui/Style.qml
- gui/controls/FpsItem.qml
- gui/controls/HeaderButton.qml
- gui/controls/Mode.qml
- gui/controls/PopupButton.qml
- gui/controls/ScopeView.qml
- gui/controls/StepCounter.qml
- gui/main.cpp
- gui/main.qml
- gui/modes/CommandPressureMode.qml
- gui/modes/HighFlowNasalCannulaMode.qml
- gui/modes/PressureAssistMode.qml
- gui/qml.qrc
Mode selection popup will allow us to change the ventilator
operation mode. The design and copies are still
under development and will be refined later.
The organization of the QML files was also changed for easy understanding:
* control/ folder keeps all Pure UI controls, like buttons and widgets
* modes/ folder keeps the implementation of all modes. Later this could be
broken down if it gets too complex.
Add stub modes: PressureAssistMode and SupportPressureMode for
testing the mode selection
> [GUI] Add initial implementation on Selection Mode Popup

- controller/lib/debug/vars.h
- controller/src/main.cpp
<git-pr-chain>
1. Set default params for NO_GUI_DEV_MODE.
Rather than starting the ventilator off, set some default values for the
NO_GUI_DEV_MODE params.
To do this, we had to modify the DebugT classes to let you specify a
default value on construction.
1. 👉 #427 Set default params for NO_GUI_DEV_MODE. 👈 **YOU ARE HERE**
1. #428 Refactor controller_debug's `debug` command.
1. #429 Sort includes in controller_debug.py.
1. #430 controller_debug: Print help for trace.
1. #431 Fix typo: seperate -> separate. …
> Set default params for NO_GUI_DEV_MODE.

- utils/controller_debug.py
<git-pr-chain>
1. Refactor controller_debug's `debug` command.
- Instead of a toggle, you specify 'debug on' or 'debug off'.
- Declare a global DbgPrint function instead of using a function
pointer.
1. 👉 #428 Refactor controller_debug's `debug` command. 👈 **YOU ARE HERE**
1. #429 Sort includes in controller_debug.py.
1. #430 controller_debug: Print help for trace.
1. #431 Fix typo: seperate -> separate.
> Refactor controller_debug's `debug` command.

- utils/controller_debug.py
<git-pr-chain>
1. controller_debug: Print help for trace.
When you run plain `trace`, print an error and also print out `trace
help`.
To accomplish this, I reformatted the do_trace docstring so there isn't
a bunch of leading whitespace.  This matches other docstrings in here.
I didn't change the content of the docstring in this change.
1. 👉 #430 controller_debug: Print help for trace. 👈 **YOU ARE HERE**
1. #431 Fix typo: seperate -> separate.
> controller_debug: Print help for trace.

- utils/controller_debug.py
<git-pr-chain>
1. Add readline to list of imports.
This makes the cmd module use readline for handling inputs, so things
like ctrl+A work.
1. 👉 #432 Add readline to list of imports. 👈 **YOU ARE HERE**
> Add readline to list of imports.

- utils/controller_debug.py
<git-pr-chain>
1. Get rid of most "global" statements.
"global" is only necessary when you assign to a global variable before
you read it.  We only have one variable like this; all of the other
"global" statements are unnecessary.
1. 👉 #433 Get rid of most "global" statements. 👈 **YOU ARE HERE**
> Get rid of most "global" statements.

- utils/controller_debug.py
<git-pr-chain>
1. Get rid of crc16 global variable.
It's unnecessary; we can just use a function.
1. 👉 #434 Get rid of crc16 global variable. 👈 **YOU ARE HERE**
> Get rid of crc16 global variable.

- platformio.ini
<git-pr-chain>
1. Build with -wno-error=sign-compare.
This warning is about doing (int)x < (unsigned int)y.
AFAICT this is all noise for us, and in fact clang doesn't even enable
it with -Wall.
1. 👉 #470 Build with -wno-error=sign-compare. 👈 **YOU ARE HERE**
1. #471 Remove unnecessary DbgPrint param from GetResp function.
1. #465 Granularity of Time and Duration 1ms -> 1us.
1. #467 Remove sample-time checking from PID.
> Build with -wno-error=sign-compare.

- utils/controller_debug.py
<git-pr-chain>
1. Remove unnecessary DbgPrint param from GetResp function.
1. 👉 #471 Remove unnecessary DbgPrint param from GetResp function. 👈 **YOU ARE HERE**
1. #465 Granularity of Time and Duration 1ms -> 1us.
1. #467 Remove sample-time checking from PID.
> Remove unnecessary DbgPrint param from GetResp function.

- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/test/pid_lib/pid_test.cpp
<git-pr-chain>
1. Revert "Removed time checks from PID library."
This reverts commit be574eaddb12501e9bfff7f74b8f7210dbe554af.
The time checks were removed from PID because we were only calling PID
from the precisely-timed control loop.  We tried to update the PID every
(say) 10ms, and we were confident we *would* call every 10ms, plus or
minus a few microseconds.  But if we happened to call with a delta of
9.99ms, the PID code would skip our sample!  That's bad.
However, for flow correction, we need our PID library to be able to
handle the case when the time interval is not constant.  In this case,
we *do* want time checks.
So in this change we add time checks back.  The next commit makes time
checking optional, so the PID library can work for both cases.
1. 👉 #462 Revert "Removed time …
> Revert "Removed time checks from PID library."

- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/src/main.cpp
- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. First pass at TV zeroing.
Uses PID to push tidal volume to zero on each breath.
The PID could use some tuning, but as a first pass, this works OK for
me.
1. 👉 #463 First pass at TV zeroing. 👈 **YOU ARE HERE**
1. #467 Remove sample-time checking from PID.
> First pass at TV zeroing.

- controller/lib/core/controller.cpp
- controller/lib/core/sensors.cpp
- controller/lib/pid/pid.cpp
- controller/lib/pid/pid.h
- controller/test/pid_lib/pid_test.cpp
This is step 3 of my evil plan: https://github.com/RespiraWorks/VentilatorSoftware/pull/462#discussion_r436893099<git-pr-chain>
1. Remove sample-time checking from PID.
Now PID recomputes every time you call Compute().  Don't want that?
Then don't call compute!
This is made possible by #465, which changes the timer granularity from
1ms to 1us.  Without that change, the clock is too granular to be used
for the high-priority loop, which runs every 10ms -- due to jitter, we
might read 9ms or 10ms when the actual values are more like 9.999ms or
10.0001ms, resulting in an amplification of error.
1. 👉 #467 Remove sample-time checking from PID. 👈 **YOU ARE HERE**
> Remove sample-time checking from PID.

- platformio.ini
<git-pr-chain>
1. Disable sign-compare by using -Wno.
Rather than disabling it via -Wno-error.  This way it's totally silent.
1. 👉 #476 Disable sign-compare by using -Wno. 👈 **YOU ARE HERE**
1. #474 Fix units errors in sensors_test.
1. #477 Move setpoint_pressure field into ControllerState.
> Disable sign-compare by using -Wno.

- controller/lib/core/actuators.h
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/src/main.cpp
<git-pr-chain>
1. Move setpoint_pressure field into ControllerState.
It doesn't belong in ActuatorState because the setpoint is not an
actuator!
1. 👉 #481 Move setpoint_pressure field into ControllerState. 👈 **YOU ARE HERE**
1. #482 Sleep for a few seconds at startup.
1. #480 Use nullptr instead of 0 for a void* param.
> Move setpoint_pressure field into ControllerState.

- controller/src/main.cpp
<git-pr-chain>
1. Sleep for a few seconds at startup.
Due to a hardware issue, the blower always spins up when the board
restarts.  Wait for the blower to spin down, otherwise the sensors will
be miscalibrated.
1. 👉 #482 Sleep for a few seconds at startup. 👈 **YOU ARE HERE**
1. #480 Use nullptr instead of 0 for a void* param.
> Sleep for a few seconds at startup.

- controller/src/main.cpp
<git-pr-chain>
1. Use nullptr instead of 0 for a void* param.
1. 👉 #480 Use nullptr instead of 0 for a void* param. 👈 **YOU ARE HERE**
> Use nullptr instead of 0 for a void* param.

- controller/lib/pid/pid.cpp
<git-pr-chain>
1. Fix formatting in pid.cpp.
Somehow escaped clang-format.
1. 👉 #494 Fix formatting in pid.cpp. 👈 **YOU ARE HERE**
1. #495 Remove trailing whitespace in sample-data/README.md
1. #485 Units: Allow x / y to return a raw ratio.
1. #486 Move blower_fsm implementations into cpp file.
> Fix formatting in pid.cpp.

- controller/lib/core/flow_integrator.cpp
- controller/lib/core/flow_integrator.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. Move flow zeroing into TVIntegrator.
1. 👉 #483 Move flow zeroing into TVIntegrator. 👈 **YOU ARE HERE**
1. #485 Units: Allow x / y to return a raw ratio.
1. #486 Move blower_fsm implementations into cpp file.
> Move flow zeroing into TVIntegrator.

- common/libs/units/units.h
- controller/test/units/units_test.cpp
<git-pr-chain>
1. Units: Allow x / y to return a raw ratio.
In a future PR, I want to divide two Durations.
Also mark more operators as const, and test that they are in fact const.
Please forgive the unironic use of pointer-to-member-function.
1. 👉 #485 Units: Allow x / y to return a raw ratio. 👈 **YOU ARE HERE**
1. #486 Move blower_fsm implementations into cpp file.
> Units: Allow x / y to return a raw ratio.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
<git-pr-chain>
1. Move blower_fsm implementations into cpp file.
Main motivation is to allow us to declare constants and functions that
are "private" to the file.
1. 👉 #486 Move blower_fsm implementations into cpp file. 👈 **YOU ARE HERE**
> Move blower_fsm implementations into cpp file.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Rise from PIP to PEEP in 100ms.
Instead of going directly from PIP to PEEP, transition over 100ms.
Citation: https://respiraworks.slack.com/archives/C011CJQV4Q7/p1591763842312500?thread_ts=1591759016.310200&cid=C011CJQV4Q7
1. 👉 #488 Rise from PIP to PEEP in 100ms. 👈 **YOU ARE HERE**
> Rise from PIP to PEEP in 100ms.

- platformio.ini
<git-pr-chain>
1. Bump gcc version to 9.2.1.
This lets us use designated initializers with fields which have
nontrivial constructors (e.g. std::optional).
This is still not a bleeding-edge gcc, so I think we should be OK.
1. 👉 #496 Bump gcc version to 9.2.1. 👈 **YOU ARE HERE**
> Bump gcc version to 9.2.1.

- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Rename setpoint_pressure -> pressure_setpoint.
To be consistent with the proto
ControllerStatus.pressure_setpoint_cm_h2o.
1. 👉 #502 Rename setpoint_pressure -> pressure_setpoint. 👈 **YOU ARE HERE**
1. #504 BlowerFsm API cleanups.
1. #505 Move volume sensing into controller.
1. #506 Delete unused VentParams.rise_time_ms.
> Rename setpoint_pressure -> pressure_setpoint.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. BlowerFsm API cleanups.
- Rename ValveState -> FlowDirection.  We no longer have an expiratory
solenoid.
- Make pressure_setpoint an std::optional instead of a Pressure plus a
boolean.
- Update out-of-date comments.
1. 👉 #504 BlowerFsm API cleanups. 👈 **YOU ARE HERE**
1. #505 Move volume sensing into controller.
1. #506 Delete unused VentParams.rise_time_ms.
> BlowerFsm API cleanups.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/lib/core/sensors.cpp
- controller/lib/core/sensors.h
- controller/src/main.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
- controller/test/controller/controller_test.cpp
- controller/test/flow_integrator/flow_integrator_test.cpp
- controller/test/sensor_tests/sensors_test.cpp
<git-pr-chain>
1. Move volume sensing into controller.
At long last.
This fixes a layering violation (sensors module shouldn't care about
breaths), and opens the door to more sophisticated volume zeroing logic.
It's also easier to test, because you don't have to compute voltages!
I had to fix an edge case in blower_fsm; our breaths were one
microsecond too long.  Not a big deal except in tests.
1. 👉 #505 Move volume sensing into controller. 👈 **YOU ARE HERE**
1. #506 Delete unused VentParams.rise_time_ms.
> Move volume sensing into controller.

- common/generated_libs/network_protocol/network_protocol.pb.h
- common/generated_libs/network_protocol/network_protocol.proto
- controller/test/comms/comms_test.cpp
- utils/network_protocol_pb2.py
<git-pr-chain>
1. Delete unused VentParams.rise_time_ms.
I didn't realize that we had this param and, in an earlier change,
hardcoded it to 100.  I guess that's...fine?  We don't expect to change
it from the GUI.
1. 👉 #506 Delete unused VentParams.rise_time_ms. 👈 **YOU ARE HERE**
> Delete unused VentParams.rise_time_ms.

- controller/lib/core/controller.cpp
- controller/lib/core/flow_integrator.h
- controller/test/controller/controller_test.cpp
- controller/test/flow_integrator/flow_integrator_test.cpp
<git-pr-chain>
1. Rename FlowIntegrator::GetTV -> GetVolume.
Tidal volume is the max patient volume over a breath.  Therefore
FlowIntegrator::GetTV, which gets the *current* volume, should be called
GetVolume.
1. 👉 #507 Rename FlowIntegrator::GetTV -> GetVolume. 👈 **YOU ARE HERE**
> Rename FlowIntegrator::GetTV -> GetVolume.

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/test/controller/controller_test.cpp
Instead of constantly when vent is Off. This should allow us to report volume when the vent is off, provided each venturi still see the flow in the correct direction when vent is off (thanks to check valves, which are lacking in our pizza builds), and provided we can take care of the drift when flow is close to zero (incoming PR with my drift correction algorithm).
> Only rezero volume when vent transitions from Off to On

- gui/app/controls/parameters/ITimeParameter.qml
- gui/app/controls/parameters/PeepParameter.qml
- gui/app/controls/parameters/PipParameter.qml
- gui/app/controls/parameters/RrParameter.qml
- gui/app/controls/readings/FlowDisplay.qml
- gui/app/controls/readings/IerDisplay.qml
- gui/app/controls/readings/PeepDisplay.qml
- gui/app/controls/readings/PipDisplay.qml
- gui/app/controls/readings/RrDisplay.qml
- gui/app/controls/readings/TvDisplay.qml
- gui/app/main.cpp
- gui/src/gui_state_container.h
We don't yet measure anything based on recent breaths but after this PR there'll be a place to plug that logic.
This PR also fixes a bug that we were using IER as I-Time. Now they are kept in sync: you command I-Time and we compute and display the "measured" (actually forced IER) based on that and on RR.
> Separates commanded and measured parameter properties in GuiStateContainer

- gui/rpi-image/rpi-primer.yml
This should allow the GUI in docker to access the pi's GPIO and UART pins that communicate with the nucleo.
> GPIO and UART privileges for Docker

- gui/app/main.cpp
- gui/src/breath_signals.h
- gui/src/gui_state_container.h
- gui/tests/breath_signals_test.h
- gui/tests/max_pressure_alarm_test.h
- gui/tests/tests.pro
- gui/tests/tst_main.cpp
This uses the breath_id signal from SensorReadings to delimit breaths and compute these values as aggregates from them in BreathSignals. Seems to produce correct values on the pre-recorded trace.
> Measures recent-breath PIP, PEEP, RR, IER

- utils/controller_debug.py
<git-pr-chain>
1. Set gui_mode last when applying a preset.
Otherwise we will do a breath with the old configuration!
1. 👉 #535 Set gui_mode last when applying a preset. 👈 **YOU ARE HERE**
1. #536 Add script to run all covent tests in a row.
> Set gui_mode last when applying a preset.

- utils/controller_debug.py
<git-pr-chain>
1. Fix calculation of IE ratio for covent tests.
Oops.
1. 👉 #544 Fix calculation of IE ratio for covent tests. 👈 **YOU ARE HERE**
1. #548 Update breath detection algorithm.
> Fix calculation of IE ratio for covent tests.

- gui/rpi-image/rpi-primer.yml
The piwiz.desktop file is responsible for the first-time boot setup wizard. Since we configure the pi with this script, it's not a very useful popup and gets in the way. If deleting the file is too extreme, I think we can just move it elsewhere like the Downloads folder. 
The --serial-port flag disables the fake data being fed to the GUI and instead connects it to the rPi's UART pins. Now, the GUI and controller actually can communicate.
> Disable boot wizard & enable serial port for data

- gui/app/main.cpp
- gui/app/main.qml
- gui/src/controller_history.h
- gui/src/gui_state_container.cpp
- gui/src/gui_state_container.h
With this change, on my machine it only takes about 6% CPU.
* We don't need the timer in QML, we can update the graphs from the controller status update signal.
* We only include points that are more than 50ms apart.
> Subsamples graph data, further improving graph performance

- controller/lib/core/actuators.cpp
- controller/lib/core/controller.cpp
- controller/lib/core/controller.h
- controller/lib/hal/psol.cpp
- controller/src/main.cpp
<git-pr-chain>
1. Initial psol control.
Not hooked up to closed-loop control yet.  What's done here is:
- We found the "active range" of the psol and encoded that.  (Below
about 80% power, the psol is fully closed, and above about 90% power,
it's completely open.)
- Added a DebugVar to control "gui_fio2"
- Added a PID controller for the psol (but not using it yet).
- Added DebugVars to force the actuators into specific positions.
Super useful for e.g. figuring out the active range of the psol.
1. 👉 #558 Initial psol control. 👈 **YOU ARE HERE**
> Initial psol control.

- gui/app/controls/graphs/PressureGraph.qml
- gui/app/controls/readings/PipDisplay.qml
- gui/app/modes/CommandPressureMode.qml
- gui/src/alarm_manager.h
- gui/src/gui_state_container.h
- gui/src/pip_not_reached_alarm.h
- gui/src/src.pro
Fixes #368 . 
Also fixes a bug that the Pressure Assist graph wasn't using the alarm.
Verified e.g. that if I tweak the commanded PIP here and there so that both alarms are active, then the alarm banner displays in red, and if I dismiss it then it's in yellow, if I dismiss that too then it disappears.
> Adds a "PIP not reached" alarm + some logic to combine it with "PIP exceeded"

- utils/run_covent_tests.py
<git-pr-chain>
1. Fix two bugs in run_covent_tests.py.
- shell-escape outfile (particularly important on Windows, where
backslash is the directory separator).
- add an explicit type to --ignore-secs, otherwise it's interpreted as a
string when you specify it.
1. 👉 #563 Fix two bugs in run_covent_tests.py. 👈 **YOU ARE HERE**
1. #561 Hook up psol PID.
1. #565 Traces of ventilator disconnect and obstruction.
> Fix two bugs in run_covent_tests.py.

- controller/lib/hal/buzzer.cpp
I was doing some tests with a dB meter on my phone and found that I could get more volume from the buzzer on the controller by slightly increasing the duty cycle.
> Adjusted the buzzer duty cycle to increase volume

- utils/controller_debug.py
- utils/run_covent_tests.py
<git-pr-chain>
1. Add fio2 support to run_covent_tests.py.
You can run the covent tests all with air from the blower, all with
pressurized air/oxygen, or some with blower and some with o2.
Also don't turn off the ventilator between tests.  Edwin requested this
so the data captured by external sources looks cleaner.  The data
captured by this script is unaffected because in any case we wait a few
seconds before starting to record.
1. 👉 #567 Add fio2 support to run_covent_tests.py. 👈 **YOU ARE HERE**
> Add fio2 support to run_covent_tests.py.

- gui/app/app.pro
- gui/app/controls/AlarmButton.qml
- gui/app/controls/AlarmNotificationBanner.qml
- gui/app/controls/HeaderButton.qml
- gui/app/controls/MainHeader.qml
- gui/app/main.qml
- gui/src/alarm_manager.h
- gui/src/latching_alarm.h
This PR is Paulo's https://github.com/RespiraWorks/VentilatorSoftware/pull/560 but with some bugfixes.
Silenced alarms widget is now bound by color and the displayed remaining silence time to the _highest-priority silenced alarm_, unlike the alarm banner, which is bound to the _highest-priority active alarm_.
Clicking the widget still does nothing.
> [GUI] Silenced alarms widget

- gui/rpi-image/rpi-primer.yml
This change adds some packages and configuration required to provision an RPi image from a basic Raspbian Buster image (instead of a desktop one.)
It also adds pulseaudio support for the login user. I haven't tested alarms yet so I'm not certain this is the correct approach here. However, this is what Ubuntu does for user audio support so I'm guessing it'll work here too.
> Install pulseaudio, lightdm, openbox, enable auto-login

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
<git-pr-chain>
1. Update gain scheduling only at breath boundaries.
The previous Ki gain scheduling in Controller would update whenever the
VentParams changed, but this is not quite right. In reality, we only
want to update when the BlowerFsm updates, at breath boundaries.
1. 👉 #571 Update gain scheduling only at breath boundaries. 👈 **YOU ARE HERE**
1. #572 Keep fan blowing during covent tests.
> Update gain scheduling only at breath boundaries.

- gui/src/gui_state_container.h
- gui/src/pip_exceeded_alarm.h
* Use commanded rather than measured RR for IER calculation in Command Pressure mode. This gets rid of unnecessary inaccuracy.
* Formatting of a number in an alarm
> A couple more GUI tweaks

- controller/lib/core/blower_fsm.cpp
- controller/lib/core/blower_fsm.h
- controller/lib/core/controller.cpp
- controller/test/blower_fsm/blower_fsm_test.cpp
This addresses @jlebar's TODO regarding renaming is_new_breath and merging FSM methods.
This change simplifies the logic for obtaining the currently desired FSM state. This allows us to get rid of intermediate state stored in the classes. Note that this slightly changes the behavior of the FSM at the breath boundary: the state returned is always the last computed state (unless we were in the OFF state).
Previous behavior was desired state from the current (possibly freshly created) instance of the FSM. Note that transitioning from off to on state is a special case: here, we will compute and return the correct "on mode" state.
> Controller fsm refactor

- gui/src/latching_alarm.h
- gui/tests/latching_alarm_test.h
Once the alarm is dismissed and the animation for dismissal starts,
the banner shows the text "(inactive)" which is unecessary.
> [GUI] Fix small glitch on Alarm Banner.

- software/common/generated_libs/network_protocol/network_protocol.pb.h
- software/common/generated_libs/network_protocol/network_protocol.proto
- software/controller/src/main.cpp
Add fio2 sensor reading to the comms interface.
I modified the network_protocol files manually, as I still can't get nanopb to run on my machine.
This is a simple change and should not bring any problem, but if someone can run nanopb on their end and give me a diff, I'll push it here.
This will require non-regression tests on the comms protocol with the GUI hooked up, which I cannot run on my own for now.
> Feed fio2 to the GUI

- .circleci/controller_tests_Dockerfile
- software/common/libs/units/units.h
- software/controller/README.md
- software/controller/lib/core/controller.cpp
- software/controller/lib/core/sensors.cpp
- software/controller/lib/core/sensors.h
- software/controller/lib/debug/debug.h
- software/controller/lib/debug/sprintf.cpp
- software/controller/lib/debug/vars.h
- software/controller/lib/hal/flash.cpp
- software/controller/lib/hal/hal.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/nvparams.cpp
- software/controller/lib/hal/nvparams.h
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/stepper.h
- software/controller/platformio.ini
- software/controller/src_test/main.cpp
- software/controller/test.sh
Clang-tidy now runs with the same checks (from .clang-tidy) on native and stm32. The issue was a missing dependency (libtinfo5) that clang-tidy needs to run in platformio checks, but it doesn't complain if it's missing.  
Cppcheck is now also working for native. 
Both clang-tidy and cppcheck checks have been added to the controller test script and set to fail on high level defects in CI.
Pertains to #132 
TODO: 
- cppcheck for stm32 (and both checks for the rest of the environments)
- clang-tidy for the GUI, probably using something like bears
> clang-tidy and cppcheck

- .circleci/controller_tests_Dockerfile
As a temporary fix for CI tests failing
> fix platformio version to 4.3.4 in CI

- .circleci/config.yml
- .circleci/gui_tests_Dockerfile
- software/gui/gui.sh
We use bear to generate a compile database when the GUI build files are created. Cppcheck and clang-tidy then use this database to check these files. See the gui-tests CI job for the results of these two checks.
Pertains to #885
> clang-tidy & cppcheck - GUI

- software/controller/README.md
This is definitely a hack to get us past the issue, and needs to be reversed when platformio team find the problem.
> Update platformio installation instructions

- .circleci/controller_tests_Dockerfile
Quick fix for errors in controller tests on CI due to platformio having dropped python2 support.
> install python 3 in dockerfile for controller

- software/common/libs/checksum/checksum.cpp
- software/common/libs/checksum/checksum.h
- software/controller/lib/core/nvparams.cpp
- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/flash.cpp
- software/controller/lib/hal/flash.h
- software/controller/lib/hal/hal.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/hal_stm32.h
- software/controller/lib/hal/hal_stm32_regs.h
- software/controller/lib/hal/i2c.cpp
- software/controller/lib/hal/i2c.h
- software/controller/lib/hal/psol.cpp
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/uart_dma.cpp
- software/controller/lib/hal/uart_dma.h
- software/controller/test/checksum/checksum_test.cpp
- software/controller/test/nvparams/nvparams_test.cpp
Add a few more references to the reference manual and datasheet in the HAL code.
Do some housekeeping. Mostly fixing spelling in comments. Made some types more consistent.  Also replaced the `typedef *REG`'s with their standard types and moved the `volatile` keyword into `typedefs` on the structs.
Planning to make a couple more passes through the HAL, but figured it would be good to checkpoint since I don't have hardware to test on.
I can run `pio test -e native` and the tests pass, and I can do a `pio run -e stm32` and everything compiles (fails to link, but that was present before - #1032)
> First pass through the HAL. Do some light editing and cleanup

- software/controller/lib/hal/i2c.cpp
- software/controller/lib/hal/i2c.h
- software/controller/lib/hal/psol.cpp
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/stepper.h
- software/controller/platformio.ini
- software/controller/src/pure_virtual.cpp
- software/controller/src_test/main.cpp
- software/controller/test/psol/psol_test.cpp
- software/controller/test/stepper/stepper_test.cpp
Fixes #1032 
`./test.sh` is now running. It fails `pio check -e `clang-tidy`, but that error was there in `master`.
I was getting a multiple definition of `main`, I think because it was linking the stm32 startup code.
`pio test -e native` - PASSES
`pio run -e stm32` - BUILD PASSES
`pio run -e integration-test - BUILD PASSES
`pio run -e stm32-test - BUILD FAILS (errors linking `dmaUART)
The `stm32-test` environment is marked experimental DMA so it was probably failing to build before. Logged as issue #1046
> Stub out the functions necessary to get ./test.sh running again

- manufacturing/internals/PSOL/README.md
- manufacturing/internals/PSOL/images/uflow_tapped.jpg
- manufacturing/internals/PSOL/images/uflow_tapping_1.jpg
- manufacturing/internals/PSOL/images/uflow_tapping_2.jpg
Added instructions for how to modify the UFlow PSOL for mounting using M3 screws. This may later have to be split off into a separate page when we have CAD of this configuration, but again as a stopgap measure at least this provides the essential information so that if someone reads this, they should not find themselves at a loss.
Updates #1055
> Uflow tapping and mounting instructions

- .circleci/controller_tests_Dockerfile
Explicitly install platformio "native" platform to get around a bug introduced in platformio 5.1.1 (see #1089 for a link to the pio issue)
Fixes #1089 : controller tests now pass on CI
> Explicitly install pio native platform for controller tests to run properly in CI

- software/controller/controller.sh
- software/controller/lib/debug/commands.h
- software/controller/lib/debug/debug_types.h
- software/controller/lib/debug/eeprom_cmd.cpp
- software/controller/lib/debug/trace.cpp
- software/controller/lib/debug/trace.h
- software/controller/lib/debug/trace_cmd.cpp
- software/controller/lib/debug/var_cmd.cpp
- software/controller/src/main.cpp
- software/controller/test/debug/eeprom_cmd_test.cpp
- software/controller/test/debug/trace_cmd_test.cpp
- software/controller/test/debug/var_cmd_test.cpp
- software/utils/controller_debug.md
- software/utils/controller_debug.py
- software/utils/controller_debug_scripts/pinch_valve_cal.py
Simplify init of the debug interface by not requiring to handle the trace buffer with debug vars, and use specific trace subcommands instead
Tested on my pizza with (among others):
```
$ ./controller_debug.py
] trace start --period 10 pressure net_flow
] trace current
Traced variables:
- pressure
- net_flow
Trace period: 10
Samples in buffer: 47
] trace graph 
```
Which graphs the desired variables, like it did before those change.
> Replace trace specific debugvars by trace subcommands

- .github/workflows/docs.yml
`gh-pages` failing because I changed the pip module used for traceability and forgot to update the Github action.
- [n/a] I have made corresponding changes to the documentation - to reflect changes in code, electrical or mechanical design
- [n/a] All new documentation or graphics follow the [documentation style guide](https://github.com/RespiraWorks/Ventilator/wiki/Documentation-style-guide)
- [n/a] All new content is linked, easily discoverable, does not require too many clicks
- [n/a] I have reviewed any other relevant parts of our [contributor wiki](https://github.com/RespiraWorks/Ventilator/wiki) to ensure that this PR conforms to the standards
> Fix Github action for gh-pages - wrong pip install

- software/controller/README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
There is currently a bug in platformio so an extra step is required to run the controller tests on native. Updating the controller README to reflect this. 
Fixes #(issue)
1089
Updates #(issue)
> add platformio manual native install instruction to controller README

- .circleci/controller_tests_Dockerfile
- software/.clang-tidy
- software/controller/controller.sh
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/stepper.h
- software/controller/platformio.ini
Make cppcheck work on stm-32 environment
Fix error in stepper driver
Enable controller static checks in CI!
Factored out the `check_*` settings in `platformio.ini` which were repeated in individual environments to apply to all environments.
We no longer get failures, which allows us to run them on CI, but there are still many warnings which we will need to get rid of.
Updates #1075
I also factored out the `check_*` settings in `platformio.ini` which were repeated in individual environments to apply to all environments.
> Remove static checks errors so we can enable them in CI

- docs/software/SRS.rst
We had several requirements ids that used the same number with different prefixes in Valispace. We decided to put all software requirements under the prefix `RW-SW-` so this PR assigned new numbers to requirements that had duplicate ids.
Fixes #1087
> De-duplicate software requirement ids

- README.md
- manufacturing/README.md
- pcb/README.md
This:
* updates disclaimers on the main page to make it clear how `master` content may be inconsistent
* explicitly links to "Releases" page as something tested but obsolete
* links to the entirety of the github pages site where requirements reside
This is not related to any issue, should simply make it easier to merge "half-baked" solutions to specific issues prior to proper integration.
> Updated disclaimers and links in prep for v0.4 changes

- software/common/libs/units/units.h
- software/controller/integration_tests/eeprom_test.h
- software/controller/lib/core/blower_fsm.cpp
- software/controller/lib/core/controller.cpp
- software/controller/lib/core/controller.h
- software/controller/lib/core/nvparams.cpp
- software/controller/lib/core/sensors.cpp
- software/controller/lib/debug/trace.cpp
- software/controller/lib/debug/trace.h
- software/controller/lib/debug/var_cmd.cpp
- software/controller/lib/debugvars/vars.h
- software/controller/lib/debugvars/vars_base.cpp
- software/controller/lib/debugvars/vars_base.h
- software/controller/lib/debugvars/vars_registry.cpp
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/psol.cpp
- software/controller/lib/pid/pid.cpp
- software/controller/lib/pid/pid.h
- software/controller/src/main.cpp
- software/controller/test/debug/interface_test.cpp
- software/controller/test/debug/trace_cmd_test.cpp
- software/controller/test/debug/trace_test.cpp
- software/controller/test/debug/var_cmd_test.cpp
- software/controller/test/debug/vars_test.cpp
- software/controller/test/pid_lib/pid_test.cpp
* the debug variable registry is now a proper singleton implementation, a single point of access and encapsulation. It ensures unique variable IDs, but unique names is still "someone else's job". For now, the python client detects name clashes.
* debug variable name may be prepended, allowing use in classes that may be multiply-instantiated and yet result in unique names; in the same way, help test may be appended to disambiguate purpose of variable
* debug variables are now part of the `Debug::Variable` namespace. Class names and member function names have been changed and updated throughout the code base.
* PID class now uses debug variables for storing its tuning parameters. Initialization requires strings to help disambiguate the parameters. There is no longer an explicit update step. …
> Debug variable improvements, explicit registry singleton, PID improvements

- software/utils/debug/controller_debug.py
Fixes issue encountered in testing:
`sn-7] trace save -p
Traceback (most recent call last):
File "./debug_cli.py", line 136, in cli_loop
return cmd.Cmd.cmdloop(self)
File "/usr/lib/python3.6/cmd.py", line 138, in cmdloop
stop = self.onecmd(line)
File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
return func(arg)
File "./debug_cli.py", line 675, in do_trace
test = self.interface.trace_save()
File "/data/RespiraWorks/VentilatorSoftware/software/utils/debug/controller_debug.py", line 330, in trace_save
time_series[len(time_series) - 1] - time_series[0]
TypeError: object of type 'Trace' has no len()`
> fix error in debug script on trace save

- software/controller/controller.sh
- software/controller/lib/core/controller.cpp
- software/controller/lib/core/controller.h
- software/controller/lib/core/sensors.cpp
- software/controller/lib/core/sensors.h
- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/hal.h
- software/controller/lib/sensors/oxygen.cpp
- software/controller/lib/sensors/oxygen.h
- software/controller/lib/sensors/pressure_sensors.cpp
- software/controller/lib/sensors/pressure_sensors.h
- software/controller/lib/sensors/sensor_base.cpp
- software/controller/lib/sensors/sensor_base.h
- software/controller/lib/sensors/venturi.cpp
- software/controller/lib/sensors/venturi.h
- software/controller/src/main.cpp
- software/controller/test/controller/controller_test.cpp
- software/controller/test/sensor_tests/sensors_test.cpp
- software/utils/debug/test_scenario.py
- software/utils/debug/test_scenarios/dummy.json
- software/utils/debug/test_scenarios/iso_pressure_tests.json
- software/utils/debug/test_scenarios/iso_volume_tests.json
* adds 5th ADC value to be read by the HAL and ADC modules - appears to have been partially implemented in the ADC module at the first position, so I have kept this convention on the level of the ADC mappings
* adds mappings for oxygen influx dP sensor in Sensors module
* removes the uncorrected flow debug variable from Sensors, as there is already one present in Controller
* removed unused dP values from sensors return struct, these used to be written to proto buffer message, but are never used, for now we zero the proto values, but should remove form definition in the future
* sensor logical mappings removed from class and made more explicit, low level pin mappings in HAL and ADC reflect physical labeling on PCBs
* New abstractions for `AnalogSensor`, `PressureSensor`, `Venturi`, etc.. …
> Sensor code refactoring

- manufacturing/internals/README.md
- software/controller/lib/core/sensors.cpp
- software/controller/lib/core/sensors.h
- software/controller/lib/hal/adc.cpp
- software/controller/lib/sensors/pressure_sensors.cpp
- software/controller/lib/sensors/pressure_sensors.h
- software/controller/test/sensor_tests/sensors_test.cpp
This PR enables us to use the interim daughter-board's analog pressure sensor. Since it supports a bigger pressure range (0-10kPa) than the ones on the mainboard (0-4kPa), it is now used for patient pressure, which is expected to be bigger than the pressure differential across a venturi.
The mainboard U3 sensor (label from its former function "Patient Pressure") can now be used to compute oxygen flow from a third venturi placed on the oxygen limb, which should allow for better oxygen control.
The setup was tested on my own board hooking both U4 pressure sensor and daughter-card analog pressure sensor to the air inlet venturi (using pneumatic Y connectors), and checking that the resulting dp matched.
Closes #1153
Followup that needs to be done: update drawings all over the manufacturing …
> Get readings for daughterboard analog pressure sensor

- software/controller/lib/core/controller.cpp
- software/controller/lib/core/controller.h
Implements rudimentary fio2 control with additional PID just for oxygen concentration. This is for testing purposes only and does not constitute a safe implementation nor guarantee interoperability with any specific ventilation modes. Pending further improvements that make use of the full flow sensor arsenal.
Updates #659
> Add rudimentary/experimental fio2 control

- .gitignore
- software/controller/.gitignore
- software/controller/integration_tests/pinch_valve_test.h
- software/controller/lib/core/actuators.cpp
- software/controller/lib/core/pinch_valve.cpp
- software/controller/lib/core/pinch_valve.h
- software/controller/lib/debug/commands.h
- software/controller/lib/debug/debug_types.h
- software/controller/lib/debug/interface.h
- software/controller/lib/debug/trace.cpp
- software/controller/lib/debug/trace.h
- software/controller/lib/debug/trace_cmd.cpp
- software/controller/lib/debug/var_cmd.cpp
- software/controller/lib/debugvars/vars.h
- software/controller/lib/debugvars/vars_base.h
- software/controller/lib/hal/circular_buffer.h
- software/controller/lib/hal/i2c.h
- software/controller/src/main.cpp
- software/controller/test/debug/trace_cmd_test.cpp
- software/controller/test/debug/trace_test.cpp
- software/controller/test/debug/var_cmd_test.cpp
- software/controller/test/debug/vars_test.cpp
- software/utils/debug/controller_debug.py
- software/utils/debug/debug_cli.py
- software/utils/debug/var_info.py
* `Debug::Variable::Base` now provides for variable size in bytes, which is forwarded to CLI, which also displays this field in verbose mode, this is to accomodate debug variables of different sizes. Generic `set_value` and `get_value` functions now operate on buffers instead of by-value.
* `VarHandler` generalizes `get` and `set` to correctly (de)serialize variables of different sizes agnostic of the actual variable type implementation.
* Implements the `FloatArray` debug variable class, which contains an `std::array<float, T>` for storage of calibration tables and the like, appropriately updates the debug command handlers and Python CLI to make use of it
* Modifies the `PinchValve` class to keep a private calibration instance to keep track of its own calibration, exposed to debug …
> FloatArray debug variable type for calibration

- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/circular_buffer.h
- software/controller/lib/hal/hal.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/i2c.cpp
- software/controller/lib/sensors/oxygen.cpp
- software/controller/lib/sensors/oxygen.h
- software/controller/lib/sensors/pressure_sensors.cpp
- software/controller/lib/sensors/pressure_sensors.h
- software/controller/lib/sensors/sensor_base.cpp
- software/controller/lib/sensors/sensor_base.h
- software/controller/lib/sensors/venturi.cpp
- software/controller/lib/sensors/venturi.h
Fixes some overlooked static check warnings. Remaining ones are either deliberate or false positives.
Note: a [recent update](https://docs.platformio.org/en/latest//core/history.html#id2) in platformio upgraded the static checkers and it looks like clang-tidy (v10 --> v12) no longer works properly (even the deliberate warnings seem gone...)
I did run the previous version of clang-tidy on this branch and it did remove lots of warnings.
List of remaining warnings and rationale behind them:
- `lib/hal/i2c.cpp:358: [low:style] Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]` ==> deliberate
- `lib/hal/hal_stm32.cpp:145: [low:style] Same expression on both sides of '-'. [duplicateExpression]` ==> deliberate: expression is `m - 1` and `m` might change in the …
> address clangtidy's warnings

- software/.clang-tidy
- software/controller/lib/core/interpolant.h
- software/controller/lib/core/pinch_valve.h
- software/controller/lib/debug/eeprom_cmd.cpp
- software/controller/lib/hal/hal.h
- software/controller/lib/non_volatile/nvparams.h
- software/controller/platformio.ini
This fixes some of the `clang-tidy` and `cppcheck` warnings that were introduced earlier in the project, and silences some of the new checks from `platformio` 5.2
Closes #1189
- [ x I have given the PR a descriptive name (prefixed with **WIP** if it is not yet ready for review)
- [ x I have tagged relevant reviewers
> Remove some warnings (including some from new tools enabled with pio 5.2.3)

- manufacturing/internals/venturi/README.md
- manufacturing/internals/venturi/images/venturi_oxygen_influx.jpg
- manufacturing/internals/venturi/venturi.ipt
- manufacturing/internals/venturi/venturi/venturi-exhale.ipt
- manufacturing/internals/venturi/venturi/venturi-influx.ipt
- manufacturing/internals/venturi/venturi/venturi-o2.ipt
- manufacturing/internals/venturi/venturi/venturi-pizza.ipt
- manufacturing/internals/venturi/venturi_assembly.iam
- manufacturing/internals/venturi/venturi_assembly/Venturi Assembly-o2.iam
Oxygen venturi now includes a diameter transition for 1/4"ID tubing. This eliminates the need for an additional adapter/fitting in the pneumatic assembly and thus simplifies manufacturing.
As an additional bug fix, the exported STL for the oxygen sensor + overpressure relief valve manifold had a very poor resolution. A new STL has been exported with sufficient resolution.
Closes #1122
> WIP: Oxygen venturi intake includes diameter transition

- .circleci/config.yml
- software/utils/rpi_config/bootstrap.sh
This will likely break deployment scripts to some extent. Doing this as contingency because of extreme and rapid drain on LFS quota lately. Pending other solutions, this is an easy and quick insurance measure to take against some obvious pitfalls that may be happening.
> anti-lfs measures

- software/controller/lib/actuators/actuator_base.h
- software/utils/debug/controller_debug.py
- software/utils/debug/scripts/valve_calibration.py
Issue: Running preset tests with the debug interface yields `Cannot set unknown variable forced_exhale_valve_pos` error message.
Recent refactoring changed some debugvar names, which are hardcoded in debug scripts. This simply changes the name of the variables to the new ones.
> Fix debugvar names in debug scripts

- software/controller/integration_tests/buzzer_test.h
- software/controller/integration_tests/eeprom_test.h
- software/controller/integration_tests/psol_test.h
- software/controller/lib/actuators/actuator_base.cpp
- software/controller/lib/actuators/actuator_base.h
- software/controller/lib/actuators/pinch_valve.h
- software/controller/lib/actuators/pwm_actuator.h
- software/controller/lib/core/actuators.cpp
- software/controller/lib/core/actuators.h
- software/utils/debug/controller_debug.py
- software/utils/debug/scripts/valve_calibration.py
> Make "forced_[actuator]_setting" debugvar names less generic

- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/dma.cpp
- software/controller/lib/hal/dma.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/i2c.cpp
- software/controller/lib/hal/i2c.h
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/stepper.h
- software/controller/lib/hal/uart_dma.cpp
- software/controller/lib/hal/uart_dma.h
Addresses several todos regarding DMA abstraction: create a `DMA::ChannelControl` class which takes care of manipulating DMA registers.
Updates #1184
Tested by running the vent, changing eeprom parameters and checking those are properly taken into account after vent restart.
modules that use DMA are:
- stepper driver
- i2c
- adc
- uart with rpi (if UART_VIA_DMA, still not fully functional)
> Abstract DMA channels and stop client module from manipulating DMA registers directly

- software/controller/lib/hal/adc.cpp
- software/controller/lib/hal/dma.cpp
- software/controller/lib/hal/dma.h
- software/controller/lib/hal/hal_stm32.cpp
- software/controller/lib/hal/i2c.cpp
- software/controller/lib/hal/i2c.h
- software/controller/lib/hal/interrupts.cpp
- software/controller/lib/hal/interrupts.h
- software/controller/lib/hal/stepper.cpp
- software/controller/lib/hal/system_timer.cpp
- software/controller/test/i2c/i2c_test.cpp
- Address todo to refactor I2C.
- Move enabling of clocks and interrupts from HAL's one time init function to the corresponding peripheral's init function (I2C and DMA for now).
- Move I2C mock class to test library.
Todo: find a way to make `i2c1` a non-global instance.
Updates #1184
Chained with #1214
As with previous hal refactoring PRs,  I ran a sanity check of the vent (run it from gui, read/write to nvparams from debug interface) and noticed no regression.
> Refactor i2c

- software/controller/platformio.ini
For some reason, pre:script in platformio.ini native environment seems to prevent the coverage reports from having correct numbers.
This means building on native `pio run -e native` will no longer work due to several undefined environment variables, e.g:
```
In file included from src/main.cpp:28:
lib/core/version.h:20:34: error: ‘GIT_VERSION’ was not declared in this scope; did you mean ‘PSTL_VERSION’?
```
> Fix coverage reports

- software/controller/lib/actuators/actuator_base.cpp
- software/controller/lib/debugvars/vars_base.cpp
- software/controller/lib/debugvars/vars_base.h
- software/controller/platformio.ini
- software/controller/test/debug/vars_test.cpp
Adds feature to append/prepend functions in debug variables library to protect against simple mistakes when using those functions.
Closes #1216
> Add delimiter charaters when appending and prepending to debugvar strings

- software/common/platformio.ini
- software/controller/platformio.ini
Issue appeared since yesterday on my computer and on CI, unit tests fail to build.
Seems related to the googletest library version being updated from 1.10 to 1.11, this fixes the problem (including on CI).
> Fix googletest version to v1.10 to allow unit testing again

- software/common/common.sh
- software/common/test_libs/custom_google/gtest_main.h
- software/controller/controller.sh
- software/controller/integration_tests/main.cpp
- software/controller/platformio.ini
Upgrade to development version of `platformio` (version `6.1.0rc1`) in order to fix coverage reports.
With that fix, coverage reports are properly generated locally and should work on CI as well.
Closes #1249
> Fix code coverage issue

- software/common/common.sh
- software/controller/controller.sh
- software/controller/lib/debug/trace.cpp
- software/controller/lib/framing/uart_stream.h
- software/controller/test/test_debug/eeprom_cmd_test.cpp
- software/controller/test/test_debug/trace_cmd_test.cpp
- software/controller/test/test_debug/var_cmd_test.cpp
- software/gui/src/qserial_output_stream.h
gcc v11 is now standard on some operating systems. Both controller and GUI have been failing to build and test because of some stricter rules for class initialization. This PR fixes the errors.
> Fixes to build and test with gcc11

- .github/workflows/docs.yml
- docs/index.rst
This PR ensures that every time generated documentation is deployed to the `gh-pages` branch, the commits are amended/squahed, so that there is only one commit on that branch.
There is no need to keep history of deployments as the `master` of this repo already tracks the history of the sources used to generate them. Minimizing the number of commits on the docs branch will also help keep the repo bloat in check.
Closes #1267
> Deploy documentation on a single commit

- software/utils/icons/rw_capture.png
- software/utils/icons/rw_logo_vertical.png
- software/utils/rpi_config/README.md
- software/utils/rpi_config/bootstrap.sh
- software/utils/rpi_config/desktop_background.jpg
- software/utils/rpi_config/update.sh
- software/utils/rpi_config/user/Desktop/vent-debug.desktop
- software/utils/rpi_config/user/Desktop/vent-update.desktop
Updates deployment scripts to only bring in graphics via LFS. Also updated desktop background and removed some unused icons.
Please follow instructions [this page](https://github.com/RespiraWorks/Ventilator/tree/issue_1277_deploy_with_graphics/software/utils/rpi_config)
to test deployment.
Some lines will need to be changed before merging to master.
Closes #1277
> Deploy with graphics

- manufacturing/peripherals.md
- software/controller/lib/non_volatile/nvparams.cpp
- software/controller/lib/non_volatile/nvparams.h
- software/controller/test/test_nvparams/nvparams_test.cpp
- software/utils/debug/controller_debug.py
- software/utils/debug/debug_cli.py
- software/utils/debug/var_info.py
This changes the `0_ventilator_serial_number` debug variable from integer to string, so we can have semantically interesting unit descriptors in it, such as `v03e2` for the 2nd enclosed prototype of the v0.3 line. Will be even more important if various spin-offs and startups start using our software.
A knock-on effect is that the non-volatile memory implementation and tests had to be updated.
To make it work, I have also updated the debug interface, which did not have facilities for serializing string debug vars. This is the first writable one.
Closes #376
> Ventilator serial number saved as string

- .circleci/config.yml
- .github/workflows/docs.yml
- .gitignore
- docs/README.md
- docs/docs.sh
- docs/purchasing/make_parts.sh
- docs/wiring/make_wiring.sh
- manufacturing/internals/blower/README.md
- manufacturing/internals/display_panel/README.md
This adds a `docs/docs.sh` script in the style of what we have for the software suites, that can:
* install dependencies
* build all documentation
* clean the build directory
* open up a browser to see a preview
Deployment scripts for github workflows and pertinent documentation have also been updated.
As a knock-on effect, wiki tutorial on how to do wiring documentation might have to be updated, @inceptionev 
Updates #1260
> Documentation scripts improved, especially for wiring assemblies

- software/utils/debug/README.md
Summary of changes
Added instructions to run unit tests locally for the debug interface.
Relevant motivation and context
Developing the interface and adding new unit tests require running unit tests locally.
Dependencies that are required for this change
None
> Instructions to run unit tests for debug interface locally

- .circleci/config.yml
`apt update` was failing on all jobs because of some packages that we don't even use.
Applied solution described here: https://support.circleci.com/hc/en-us/articles/360051749992-Build-Fails-Using-apt-get-update-Command
Also used the opportunity to update our packages to the currently supported LTS images of Ubuntu 2022-04.
Closes #1319
> Fixed CircleCI Ubuntu image bug and updated VM images

- .github/workflows/docs.yml
- docs/lychee.toml
- software/controller/controller.sh
- software/gui/gui.sh
Recent attempt to do a fresh deploy to the v0.3 enclosed in Maryland resulted in some issues:
* bootstrap script failed out because looks like a line was commented out that sources .profile to make conan executable visible
* the URL changed for downloading the platformio udev rules
CMake scripts for conan v.2.0 are still not on the main channel, so the ticket must remain open as we periodically check for updates.
Updates #1324
> Routine deployment and CI script maintenance

- software/common/common.sh
- software/controller/README.md
- software/controller/controller.sh
- software/controller/lib/debug/interface.cpp
- software/controller/lib/debug/interface.h
- software/controller/platformio/build_config/auto_firmware_version.py
* bumped to latest platformio version
* updated related installation/configuration/build scripts
* updated debug interface to use `<array>` as current implementation fails on newer compilers (GCC 12.2.0 in this case)
* few additional changes to address new clang-tidy warnings
* note, additional clang-tidy warnings abound throughout the rest of the code, but only fixing in files touched by the purpose of this PR
* regression validated with integration and lung-in-the-loop tests
* simplified controller README, because many of the manual config steps are now done by our script and we don't want to have double the maintenance burden.
> Platformio version bump

- .github/.codecov.yml
- software/common/common.sh
Codecov have deprecated the pip package for their uploader:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
Turns out we are already using their uploader correctly, but there was still a line to install the old pip package.
This has been eliminated.
Furthermore, the upload token has been renewed, removed from the repo and is now an environment variable provided by circleci. Security hole plugged.
> Removes installation of deprecated codecov pip package

- .circleci/config.yml
- .gitignore
- docs/lychee.toml
- software/common/common.sh
- software/controller/controller.sh
- software/design/GUI_alarm_subsystem.md
- software/design/README.md
- software/design/UI_requirements.md
- software/design/milestone_v0.2.md
- software/gui/CMakeLists.txt
- software/gui/CMakeUserPresets.json
- software/gui/cmake/ConanConfig.cmake
- software/gui/conanfile.txt
- software/gui/gui.sh
- software/gui/src/gui_state_container.cpp
General CI update that ensure all builds and tests pass.
* `gui` project updated to use Conan v.2, seeing as Conan v1.6 is now deprecated and many packages are not updated for it
* using the new Codecov coverage uploader utility directly from CircleCI orbs.
* `common`, `controller` and `gui` build scripts updated to no longer use `codecov-cli` utility but instead assume external tool is used.
* A number of links to google docs updated to pass link checker
* A number of google docs had access settings updated to allow public viewer access
* Raspberry pi links excluded from link checker, as their server appears to block the crawler
- ~[ ] All tests pass - new and old, locally and on CI~
- Tests passing on CI and locally
- Do not have a ventilator to deploy and test with hardware, so no …
> Maintain/update CI: Conan2, CodeCov upload script, dead links
